#ifndef CY_SHADER_SOURCE_H
#define CY_SHADER_SOURCE_H
// Where shader source comes from, and the one door **generated** source comes through. Tasks 3.1
// and 3.8.
//
// --- TASK 3.8 IS A SEAM, NOT A FEATURE ------------------------------------------------------------
//
// `shader-system` — "Material shader generation" and "Compute and utility shaders": material
// shaders generated by the material compiler (M7) and compute kernels generated by the VFX graph
// compiler "SHALL be emitted as Slang and SHALL pass through this same pipeline", with no second
// toolchain, no separate cache, and no backend-specific source.
//
// **`SourceStore` is that entry point.** A generator calls `add_generated()` with Slang text and a
// logical module name; everything downstream — the compiler, the permutation domain, the cache key,
// the shader library, hot reload, the pipeline manifest — treats the result exactly as it treats a
// file on disk, because by the time it is a `ShaderSource` there is nothing left to tell them apart
// except the `origin` field, and only the build report reads that.
//
// Three consequences worth stating, because they are what "same pipeline" has to mean:
//
//   * **Deduplication is by content hash, not by name.** `shader-system` requires that "materials
//     producing identical source share one program and one pipeline". Two generators that emit
//     byte-identical text get one `SourceId` and therefore one cache entry, whatever they called it.
//   * **Imports resolve uniformly.** A generated module may `import cy.brdf`, and a hand-authored
//     shader may import a generated module. Resolution goes through this store either way, which is
//     what makes the standard library usable from generated code without a second search path.
//   * **Generated text is retrievable.** The specification's "Generated source is inspectable"
//     scenario is `text_of()` — in development builds the store keeps the bytes, so a misbehaving
//     generated kernel can be read rather than guessed at.
//
// --- WHY THE STORE OWNS THE BYTES -----------------------------------------------------------------
//
// A `ShaderSource` is a handle plus metadata, never a pointer into a caller's buffer. The compiler
// runs on job workers (hot reload, `shader-system`) and a generator's buffer does not outlive the
// call that produced it. One arena of text with interned ranges is also what makes the content hash
// of a *resolved* source — the module plus everything it imports — computable without walking a
// tree of separately-owned strings.

#include <cy/core/base/expected.h>
#include <cy/core/memory/array.h>
#include <cy/shader/shader.h>

#include <string_view>

namespace cy::shader {

/// Where a source module came from. The pipeline does not branch on this; the build report does.
enum class SourceOrigin : u8 {
    /// Read from the filesystem — a `.slang` file under the project's or the engine's shader root.
    File = 0,
    /// Emitted by a generator: the material compiler at M7, the VFX graph compiler afterwards.
    Generated = 1,
};

const char* source_origin_name(SourceOrigin origin) noexcept;

/// A handle onto one module in a `SourceStore`. Stable for the life of the store; invalidated by
/// nothing except `clear()`, so a library entry may hold one across a reload.
struct SourceId {
    u32 value = 0;

    [[nodiscard]] bool valid() const noexcept { return value != 0; }
    friend bool operator==(SourceId a, SourceId b) noexcept { return a.value == b.value; }
    friend bool operator!=(SourceId a, SourceId b) noexcept { return a.value != b.value; }
};

/// One module's identity, as everything downstream sees it.
///
/// `module_name` is the name an `import` resolves against — `cy.brdf`, not `cy/brdf.slang`. `path`
/// is where it came from, and is a synthetic `generated:` path for emitted source, which is what
/// makes a diagnostic on generated code point somewhere a human can act on.
struct ShaderSource {
    SourceId id;
    SourceOrigin origin = SourceOrigin::File;
    /// The dotted module name. Empty for a source that is not importable — a leaf entry-point file.
    std::string_view module_name;
    /// A path for diagnostics: a real one for `File`, `generated:<name>` for `Generated`.
    std::string_view path;
    /// The module's own text, without its imports. Empty when a `File` module has not been read yet.
    std::string_view text;
    /// BLAKE3 over `text`. The deduplication key, and one input to the cache key.
    ContentHash text_hash;
    /// Set for a `File` module when the file was read; used by hot reload to notice a change that
    /// the watcher reported for a path this store holds.
    i64 modified_ns = 0;
};

/// Statistics a build report asks for, and a leak test asserts on.
struct SourceStoreStats {
    u32 modules = 0;
    u32 generated = 0;
    /// Modules a second `add_generated()` matched by content hash rather than storing again. This is
    /// "two materials share a pipeline" measured at its origin.
    u32 deduplicated = 0;
    u64 text_bytes = 0;
};

/// Every module the compiler may see, by whatever route it arrived.
///
/// Not thread-safe. Compilation runs on job workers, but *resolution* happens once on the thread
/// that assembles a compile request, and a store behind a lock would invite a generator to publish
/// into it while a worker walks it. Publishing is a main-thread act, like every other structural
/// change in this engine.
class SourceStore {
public:
    explicit SourceStore(Allocator& allocator) noexcept;

    SourceStore(const SourceStore&) = delete;
    SourceStore& operator=(const SourceStore&) = delete;

    /// Add a search root for `File` modules. `import cy.brdf` looks for `<root>/cy/brdf.slang` in
    /// the roots in the order they were added, so a project root added after the engine's overrides
    /// nothing and a project root added before it overrides everything — which is the choice a
    /// project makes, not one this class makes for it.
    [[nodiscard]] Status add_root(const char* directory) noexcept;

    /// Publish generated Slang source under a module name. **This is task 3.8's entry point.**
    ///
    /// Idempotent by content: adding text whose hash matches a module already present returns that
    /// module's id and counts a deduplication, so a thousand materials that lower to the same source
    /// produce one program. Adding *different* text under a name already taken replaces it and
    /// returns the same id, so a regenerated material does not leak a module per edit.
    [[nodiscard]] Expected<SourceId, Error> add_generated(const char* module_name,
                                                          std::string_view text) noexcept;

    /// Resolve a module name to a module, reading it from a root if it is a file that has not been
    /// read yet. Generated modules shadow files of the same name: a generator that overrides a
    /// standard-library module is doing so deliberately.
    [[nodiscard]] Expected<SourceId, Error> resolve(const char* module_name) noexcept;

    /// Register a file that is not importable — an entry-point shader named by path rather than by
    /// module name. Returns the same id for the same path.
    [[nodiscard]] Expected<SourceId, Error> add_file(const char* path) noexcept;

    /// Re-read a `File` module from disk, replacing its text and hash. Returns true when the content
    /// hash changed, which is what hot reload branches on: a watcher event whose file is unchanged
    /// costs a read and nothing else.
    [[nodiscard]] Expected<bool, Error> refresh(SourceId id) noexcept;

    [[nodiscard]] ShaderSource get(SourceId id) const noexcept;
    /// The module's text. `shader-system`'s "Generated source is inspectable" scenario.
    [[nodiscard]] std::string_view text_of(SourceId id) const noexcept;
    /// Find by module name without reading anything. Invalid when the name is not present.
    [[nodiscard]] SourceId find(const char* module_name) const noexcept;
    /// Find by the path a module was read from or synthesised for.
    [[nodiscard]] SourceId find_by_path(const char* path) const noexcept;

    [[nodiscard]] u32 size() const noexcept { return static_cast<u32>(modules_.size()); }
    /// Iterate every module, in the order they were added — which is deterministic across runs,
    /// because a build report that lists shaders in hash-map order is a report that never diffs.
    [[nodiscard]] ShaderSource at(u32 index) const noexcept;

    [[nodiscard]] SourceStoreStats stats() const noexcept { return stats_; }

    void clear() noexcept;

private:
    /// A range in `text_`, so that hundreds of modules cost one allocation rather than hundreds.
    struct Range {
        u32 offset = 0;
        u32 length = 0;
    };

    struct Module {
        Range name;
        Range path;
        Range text;
        ContentHash hash;
        i64 modified_ns = 0;
        SourceOrigin origin = SourceOrigin::File;
    };

    [[nodiscard]] std::string_view text_at(Range range) const noexcept {
        return {text_.data() + range.offset, range.length};
    }
    [[nodiscard]] Expected<Range, Error> intern(std::string_view text) noexcept;
    [[nodiscard]] Expected<SourceId, Error> add(std::string_view module_name, std::string_view path,
                                                std::string_view text, SourceOrigin origin,
                                                i64 modified_ns) noexcept;
    /// Build `<root>/<module path>.slang` for each root and return the first that exists.
    [[nodiscard]] Expected<u32, Error> locate(const char* module_name, char* out,
                                              usize capacity) const noexcept;

    Allocator* allocator_;
    Array<char> text_;
    Array<Module> modules_;
    Array<Range> roots_;
    SourceStoreStats stats_;
};

/// The engine's own shader root, relative to the repository or the installed data directory:
/// `src/rendering/shaders/`. Declared here rather than in a build-generated header because it is
/// content layout, not build configuration — the cook step and the editor both need it and neither
/// should have its own copy of the string.
inline constexpr const char* kEngineShaderRoot = "src/rendering/shaders";

/// The file extension every source module carries. Slang, always: a generator that emits anything
/// else has introduced the second toolchain this module exists to prevent.
inline constexpr const char* kSourceExtension = ".slang";

}  // namespace cy::shader

#endif  // CY_SHADER_SOURCE_H
