#pragma once
// Compiled DXIL for samples/03-first-light. GENERATED by embed_dxil.py.
// The one-byte placeholders deliberately fail D3D12 pipeline creation until regenerated.

#include <cy/core/base/types.h>

namespace cy::sample::first_light {
inline constexpr u8 kFirstLightShadowVertexDxil[] = {0};
inline constexpr u8 kFirstLightForwardVertexDxil[] = {0};
inline constexpr u8 kFirstLightForwardFragmentDxil[] = {0};
}  // namespace cy::sample::first_light
