#pragma once
// Generating a navigation tile from source geometry: the voxelisation boundary, and the one place
// in this engine that may name a Recast symbol. M8.b task 6.1.
//
// ================================================================================================
// THE LINE BETWEEN ENGINE CODE AND AN INTEGRATED ALGORITHM, STATED ONCE
// ================================================================================================
//
// `ai-system` draws it: "Proven algorithms MAY be integrated where they are not differentiating —
// navmesh generation and pathfinding continue to use the navigation stack's dependencies." Navmesh
// generation is that step and Recast is that algorithm; `navigation` describes it procedurally —
// "generated by VOXELISING source geometry and EXTRACTING WALKABLE SURFACES, parameterised by: cell
// size and height, agent radius, height, maximum climb, and maximum slope; region minimum and merge
// sizes; edge maximum length and error; and detail sample distance and error" — which is the
// parameter list of `rcConfig` written out in prose.
//
// EVERYTHING ABOVE THIS FUNCTION IS ENGINE-OWNED: the runtime representation (navmesh.h), tiling
// and cross-tile adjacency, A* and the funnel (query.h), the region hierarchy (hierarchy.h), flow
// fields (flow_field.h), avoidance and crowds (crowd.h). Detour, Recast's own runtime half, is
// deliberately NOT integrated — navmesh.h's header carries that argument in full.
//
// ================================================================================================
// WHY THERE ARE TWO IMPLEMENTATIONS AND WHY BOTH ARE COMPILED
// ================================================================================================
//
// `build_tile()` has two back ends and one contract:
//
//   * `NavBuildBackend::Recast` — Recast's rasteriser, region builder and contour tracer, so a
//     tile's polygons are the merged convex regions Recast produces. Available when `CY_NAVIGATION`
//     is on, which is its default.
//   * `NavBuildBackend::Engine` — an engine-owned rasteriser that voxelises the same triangles
//     under the same parameters and emits one quad per walkable cell. Same filters, same slope and
//     climb limits, same erosion, same area marking, same tile; MORE POLYGONS, because it does not
//     merge them into larger convex regions. A path over it is the same path; a search over it
//     expands more nodes.
//
// The second exists because `build-system-and-platforms` requires a disabled feature to fetch,
// build and link nothing — with `CY_NAVIGATION` off this is the only back end there is — and
// because a boundary only one configuration compiles is a boundary nobody has checked.
//
// IT IS A PARAMETER RATHER THAN AN `#if` FOR ONE REASON: it lets `tests/test_build.cpp` assert the
// same contract over BOTH back ends in ONE build — walkable area survives, an eroded gap does not,
// a steep face is rejected, and the two meshes carry paths between the same pairs of points. A
// difference that only appears in the configuration nobody builds is a difference nobody finds.
//
// ================================================================================================
// FILTERING IS A DECLARATION, NOT A CALLBACK
// ================================================================================================
//
// `navigation`: "Generation SHALL support filtering by layer, by tag, and by an explicit
// include/exclude volume." All three are fields of `NavBuildParams`, applied to `NavSourceGeometry`
// before a triangle is rasterised, so the same geometry cooked with two filters produces two tiles
// and neither call knows anything about the other. A callback would make a cook depend on the
// caller's state, and a cook that depends on caller state is not reproducible.

#include <cy/core/base/expected.h>
#include <cy/core/math/shapes.h>
#include <cy/core/math/vec.h>
#include <cy/core/memory/array.h>
#include <cy/navigation/navmesh.h>

namespace cy::navigation {

/// Which implementation extracts the walkable polygons. See the header.
enum class NavBuildBackend : u8 {
    /// Recast when this build has it, the engine's own rasteriser when it does not.
    Automatic = 0,
    Engine,
    /// Refused with `Unsupported` when `CY_NAVIGATION` is off, rather than silently downgraded: a
    /// cook that asked for merged regions and got quads would produce a different mesh under the
    /// same parameters, and that is exactly the kind of difference a cook key exists to catch.
    Recast,
};

/// The parameters `navigation` names, in the order it names them.
struct NavBuildParams {
    // Voxelisation.
    f32 cell_size = 0.3F;
    f32 cell_height = 0.2F;
    // The agent the mesh is for. `AgentProfile` carries the same four values at runtime; they are
    // repeated here because a build is a cook step that may run with no mesh in existence yet.
    f32 agent_radius = 0.5F;
    f32 agent_height = 2.0F;
    f32 agent_max_climb = 0.4F;
    f32 agent_max_slope_degrees = 45.0F;
    // Regions.
    f32 region_min_size = 8.0F;
    f32 region_merge_size = 20.0F;
    // Contours.
    f32 edge_max_length = 12.0F;
    f32 edge_max_error = 1.3F;
    // Detail.
    f32 detail_sample_distance = 6.0F;
    f32 detail_sample_max_error = 1.0F;

    // Filters. A triangle survives when its layer is in `layers`, its tag is in `tags`, it is
    // inside every include volume (or there are none), and outside every exclude volume.
    u64 layers = ~u64{0};
    u64 tags = ~u64{0};
    Span<const Aabb> include_volumes;
    Span<const Aabb> exclude_volumes;

    NavBuildBackend backend = NavBuildBackend::Automatic;
};

/// The triangles a tile is built from, plus the per-triangle classification the filters read.
///
/// Indices are triples. `layer`, `tag` and `area`, when non-empty, are one entry per TRIANGLE — a
/// triangle whose arrays are shorter than the index count takes layer 0, tag 0 and `kAreaGround`,
/// which is what a caller that has no classification to give should pass.
struct NavSourceGeometry {
    Span<const Vec3> vertices;
    Span<const u32> indices;
    Span<const u8> layer;
    Span<const u8> tag;
    Span<const AreaType> area;
};

/// What a build did, so a cook reports rather than claims.
struct NavBuildReport {
    u32 triangles_in = 0;
    u32 triangles_filtered = 0;  ///< dropped by layer, tag or volume
    u32 triangles_steep = 0;     ///< dropped by the slope limit
    u32 spans = 0;               ///< walkable voxel columns after erosion
    u32 polys = 0;
    u32 vertices = 0;
    /// Which back end actually ran. Never `Automatic`, so a cook records what produced a tile
    /// rather than what it asked for.
    NavBuildBackend backend = NavBuildBackend::Engine;
};

/// Is this build linked against Recast? `CY_NAVIGATION`, read as a value rather than as an `#if` at
/// every call site, so a caller can report which back end produced a tile.
[[nodiscard]] bool recast_available() noexcept;

/// Voxelise `geometry` and extract the walkable polygons of one tile.
///
/// `bounds` is the tile's own extent in world space, which the caller derives from `NavMesh`'s tile
/// layout — navigation owns its tiling and this function does not invent one. The result is ready
/// for `NavMesh::add_tile`.
[[nodiscard]] Expected<NavTileData, Error> build_tile(Allocator& allocator,
                                                      const NavBuildParams& params,
                                                      const NavSourceGeometry& geometry,
                                                      TileCoord coord, const Aabb& bounds,
                                                      NavBuildReport& report) noexcept;

}  // namespace cy::navigation
