#pragma once
// SPDX-License-Identifier: MIT
// `.cube` text for the post suites, generated from a mapping so the expected output of every
// lattice point is known by construction.

#include <cy/core/base/types.h>
#include <cy/core/math/vec.h>
#include <cy/rendering/post/lut.h>
#include <cy/test/test.h>

#include <cstdio>
#include <string>
#include <vector>

namespace cy::post_test {

using cy::f32;
using cy::u32;
using cy::usize;
using cy::Vec3;

/// A `.cube` of edge `size` whose entry at each lattice point is `map` of that point, red fastest.
template <typename Map>
std::string cube_text(u32 size, Map map, const char* header = "") {
    std::string text = "# generated by the test\nTITLE \"test\"\n";
    text += header;
    text += "LUT_3D_SIZE " + std::to_string(size) + "\n";
    const f32 step = 1.0F / static_cast<f32>(size - 1U);
    char line[96];
    for (u32 b = 0; b < size; ++b) {
        for (u32 g = 0; g < size; ++g) {
            for (u32 r = 0; r < size; ++r) {
                const Vec3 out = map(Vec3{static_cast<f32>(r) * step, static_cast<f32>(g) * step,
                                          static_cast<f32>(b) * step});
                (void)std::snprintf(line, sizeof(line), "%.6f %.6f %.6f\n",
                                    static_cast<double>(out.x), static_cast<double>(out.y),
                                    static_cast<double>(out.z));
                text += line;
            }
        }
    }
    return text;
}

/// Red takes green's value, green blue's and blue red's: a permutation, so its expected output for
/// any input is known exactly.
inline Vec3 rotate_channels(Vec3 in) noexcept {
    return Vec3{in.y, in.z, in.x};
}

inline std::vector<Vec3> bake(const cy::rendering::DisplayGrade& grade,
                              u32 size = cy::rendering::kDisplayLutSize) {
    std::vector<Vec3> table(static_cast<usize>(size) * size * size);
    CY_REQUIRE(cy::rendering::bake_display_lut(grade, size, table.data(), table.size()));
    return table;
}

}  // namespace cy::post_test
