#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Write content/beauty/looks/cool.cube, the beauty shot's cool look, from its formula.

A `.cube` is what a colourist's tool exports, and the engine reads one exactly as it would read an
exported file: indexed by sRGB-ENCODED values, red fastest. This script is where the committed file
comes from, so the look is a formula a reviewer can read rather than 35 937 numbers.

    python3 samples/12-beauty/make_cool_look.py

The look, in the encoded domain, per lattice point x with luma y:
    shadows (weight (1 - y)^2) lean teal:   + (-0.035, +0.010, +0.050)
    highlights (weight y^2) lean steel:     + (-0.020,  0.000, +0.025)
    saturation 0.9 about y, then a gentle S-curve about 0.5 of strength 0.08.
"""

import pathlib

SIZE = 17
OUT = pathlib.Path(__file__).resolve().parents[2] / "content" / "beauty" / "looks" / "cool.cube"


def clamp(value: float) -> float:
    return min(max(value, 0.0), 1.0)


def look(r: float, g: float, b: float) -> tuple[float, float, float]:
    y = 0.2126 * r + 0.7152 * g + 0.0722 * b
    shadow = (1.0 - y) ** 2
    highlight = y * y
    out = [r + shadow * -0.035 + highlight * -0.020,
           g + shadow * 0.010,
           b + shadow * 0.050 + highlight * 0.025]
    out = [y + (c - y) * 0.9 for c in out]
    out = [c + 0.08 * (c - 0.5) * (1.0 - abs(2.0 * c - 1.0)) for c in out]
    return tuple(clamp(c) for c in out)


def main() -> int:
    lines = [
        "# content/beauty/looks/cool.cube — the beauty shot's cool look. GENERATED by",
        "# samples/12-beauty/make_cool_look.py, whose docstring is the formula. sRGB-encoded input,",
        "# red fastest, as an exported creative LUT is; cool.cygrade reads it in that encoding.",
        'TITLE "Cyberdyne cool"',
        f"LUT_3D_SIZE {SIZE}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
    ]
    step = 1.0 / (SIZE - 1)
    for b in range(SIZE):
        for g in range(SIZE):
            for r in range(SIZE):
                lines.append("%.6f %.6f %.6f" % look(r * step, g * step, b * step))
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
