#pragma once
// Where shader source comes from — and the seam engine-*generated* source arrives through.
// Tasks 3.1 and 3.8.
//
// `shader-system` is explicit that generated source is not a second toolchain: "Engine-generated
// shader source — material shaders generated from material definitions, and compute kernels
// generated by the VFX graph compiler — SHALL be emitted as Slang and SHALL pass through this same
// pipeline. Generators SHALL NOT emit backend-specific source, introduce a second shader toolchain,
// or maintain a separate cache."
//
// THIS FILE IS THAT SENTENCE MADE STRUCTURAL. A `SourceUnit` is a named body of Slang text and an
// `origin`. `SourceOrigin::Authored` means it was read from the virtual filesystem;
// `SourceOrigin::Generated` means a generator handed it over. NOTHING DOWNSTREAM OF HERE BRANCHES
// ON THAT FIELD — the compiler, the reflection, the cache key, the library and the hot-reload path
// all take a `SourceUnit` and cannot tell the two apart. The field exists so that a diagnostic can
// say which it was and so that `origin_generated()` can answer "is this inspectable generated
// source", which `shader-system`'s "Generated source is inspectable" scenario requires.
//
// M7'S ENTRY POINT IS `SourceRegistry::add_generated()`. The material compiler lowers a material to
// Slang, calls it once with the module name it chose, and then compiles that module name exactly as
// a hand-authored one is compiled. It never touches the cache, the compiler or the library
// directly. That is the whole of the integration, and it is why this header is small.
//
// MODULE NAMES, NOT FILE PATHS, ARE THE CURRENCY. `import cy.brdf` in a Slang file names a module;
// the registry maps a module name onto a path under its root (`cy.brdf` -> `cy/brdf.slang`) for the
// authored case and onto an in-memory unit for the generated one. A compiler backend resolves
// imports through `SourceRegistry::resolver()` and therefore resolves a generated module the same
// way it resolves a file — which is what "no separate path" means when it is executable rather
// than aspirational.

#include <cy/core/assets/hash.h>
#include <cy/core/assets/path.h>
#include <cy/core/assets/vfs.h>
#include <cy/core/base/expected.h>
#include <cy/core/memory/array.h>
#include <cy/core/values/name.h>

#include <string_view>

namespace cy::shader {

/// The file extension the engine's shader source uses. Slang, and only Slang: `shader-system`
/// adopts one authoring language and the engine does not author a second.
inline constexpr std::string_view kSourceExtension = ".slang";

/// The separator in a module name. `cy.brdf` is the module in `cy/brdf.slang`.
inline constexpr char kModuleSeparator = '.';

enum class SourceOrigin : u8 {
    /// Read from the virtual filesystem, authored by a person.
    Authored = 0,
    /// Emitted by an engine generator — the material compiler at M7, the VFX graph compiler after
    /// it. Compiled, reflected, cached and hot-reloaded identically.
    Generated = 1,
};

const char* source_origin_name(SourceOrigin origin) noexcept;

/// One body of shader source, and where it came from.
///
/// `text` is borrowed from the `SourceRegistry` that produced this unit and is valid until that
/// unit is replaced or removed. Nothing here owns storage, so a `SourceUnit` is cheap to copy and
/// safe to put in a compile request.
struct SourceUnit {
    /// `cy.brdf`, `material.4f3a...`. The name an `import` resolves and the cache keys against.
    Name module_name;
    /// The authored file. Empty for a generated unit, which has no file — deliberately, so that a
    /// generator cannot smuggle a private on-disk cache in beside the engine's.
    assets::VirtualPath path;
    SourceOrigin origin = SourceOrigin::Authored;
    /// Which generator produced it: `material-compiler`, `vfx-graph`. Empty when authored. A
    /// diagnostic names it, so "the shader is broken" and "the generator emitted broken Slang" are
    /// distinguishable, which `shader-system`'s "The boundary is explicit" scenario requires.
    Name generator;
    Span<const char> text;
    /// BLAKE3 over `text`. The first component of every derived key: two materials that lower to
    /// identical source have identical hashes and therefore share one program and one pipeline,
    /// which is `shader-system`'s "Two materials share a pipeline" scenario.
    assets::ContentHash hash;
};

/// How a compiler back end asks for a module it saw in an `import`.
///
/// A function pointer and a user pointer rather than a virtual interface: a Slang session wants a
/// C-callable file system and a plain pair converts into one without a shim that owns anything.
/// Returns false when the module is unknown, which is the back end's cue to report an unresolved
/// import at the source location of the `import` itself.
using SourceResolveFn = bool (*)(void* user, std::string_view module_name,
                                 SourceUnit& out) noexcept;

struct SourceResolver {
    SourceResolveFn resolve = nullptr;
    void* user = nullptr;

    [[nodiscard]] bool operator()(std::string_view module_name, SourceUnit& out) const noexcept {
        return resolve != nullptr && resolve(user, module_name, out);
    }
};

/// The set of source modules a compilation can see: files under a root, plus whatever a generator
/// has published.
///
/// Not thread-safe. It reads files, so it is called from a thread where blocking is legal — the
/// same contract `cy::assets::FileWatcher` states, and for the same reason.
class SourceRegistry {
public:
    explicit SourceRegistry(Allocator& allocator) noexcept;

    SourceRegistry(const SourceRegistry&) = delete;
    SourceRegistry& operator=(const SourceRegistry&) = delete;

    /// Attach to a namespace and the directory authored modules are rooted at. The registry holds
    /// no ownership of the filesystem and must not outlive it. A registry with no filesystem still
    /// works — it then holds generated modules only, which is what a cook step driven entirely by
    /// the material compiler looks like.
    [[nodiscard]] Status start(assets::VirtualFileSystem& files,
                               const assets::VirtualPath& root) noexcept;
    void stop() noexcept;

    [[nodiscard]] const assets::VirtualPath& root() const noexcept { return root_; }

    /// Read an authored module in, or return the copy already read.
    ///
    /// `reload` re-reads it even when it is resident, which is what the hot-reload path calls after
    /// the watcher reports the file settled.
    [[nodiscard]] Expected<SourceUnit, Error> load(Name module_name) noexcept;
    [[nodiscard]] Expected<SourceUnit, Error> reload(Name module_name) noexcept;

    /// Publish generated source under `module_name`. **This is M7's entry point** — see the header.
    ///
    /// Replaces any unit already published under that name, so a regenerated material overwrites
    /// its predecessor rather than accumulating. `generator` names who produced it and may not be
    /// empty: an anonymous generated module is one nobody can attribute a bad diagnostic to.
    [[nodiscard]] Expected<SourceUnit, Error> add_generated(Name module_name, Name generator,
                                                            std::string_view text) noexcept;

    /// The unit under `module_name`, written into `out`. False when there is none. Never reads a
    /// file: a caller that wants the file read calls `load`.
    ///
    /// An out-parameter rather than a returned pointer, because a `SourceUnit` is a projection of
    /// the registry's own entry rather than an object it stores — returning a pointer would mean
    /// keeping a second copy of every field alive purely to have something to point at.
    [[nodiscard]] bool find(Name module_name, SourceUnit& out) const noexcept;
    [[nodiscard]] bool contains(Name module_name) const noexcept;
    [[nodiscard]] Status remove(Name module_name) noexcept;
    void clear() noexcept;

    [[nodiscard]] usize size() const noexcept { return units_.size(); }
    /// Every resident unit, in the order they were added. Ordering is stable so a report over the
    /// registry is reproducible.
    [[nodiscard]] SourceUnit unit_at(usize index) const noexcept;

    /// A resolver over this registry, for a compiler back end's import handling.
    [[nodiscard]] SourceResolver resolver() noexcept;

    /// The path an authored module would be read from: `root/<name with '.' as '/'>.slang`.
    [[nodiscard]] Expected<assets::VirtualPath, Error> path_for(Name module_name) const noexcept;

    /// The module name a path under the root denotes — the inverse of `path_for`, and what the
    /// hot-reload path uses to turn a watcher event back into a module. Fails for a path outside
    /// the root or without the `.slang` extension.
    [[nodiscard]] Expected<Name, Error> module_for(const assets::VirtualPath& path) const noexcept;

private:
    /// A unit and the storage its text lives in. `Array<char>` keeps its buffer on the heap, so
    /// growing `units_` moves the entry without moving the text, and a `SourceUnit` handed out
    /// earlier keeps pointing at the same bytes.
    struct Entry {
        Name module_name;
        assets::VirtualPath path;
        SourceOrigin origin = SourceOrigin::Authored;
        Name generator;
        assets::ContentHash hash;
        Array<char> text;
    };

    [[nodiscard]] usize find_index(Name module_name) const noexcept;
    [[nodiscard]] Expected<usize, Error> store(Name module_name, const assets::VirtualPath& path,
                                               SourceOrigin origin, Name generator,
                                               std::string_view text) noexcept;
    [[nodiscard]] static SourceUnit unit_of(const Entry& entry) noexcept;
    static bool resolve_thunk(void* user, std::string_view module_name, SourceUnit& out) noexcept;

    Allocator* allocator_;
    assets::VirtualFileSystem* files_ = nullptr;
    assets::VirtualPath root_;
    Array<Entry> units_;
    Array<u8> scratch_;
};

}  // namespace cy::shader
