#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Rewrite src/ui/text/src/builtin_font_data.h from the X11 `misc-fixed` 6x13 font.

    python3 src/ui/text/tools/make_builtin_font.py [--pcf /usr/share/fonts/X11/misc/6x13.pcf.gz]

THE FONT IS A STAND-IN. The engine has no font import, rasteriser or glyph atlas from real fonts yet
(`text-and-fonts`, issue #86), and the runtime interface needs SOME glyphs to put a console and a HUD
on screen. `misc-fixed` 6x13 is the X Window System's terminal font, released into the public domain
("Public domain font. Share and enjoy."), and it is what most Linux terminals drew for twenty years.
This script reads its printable ASCII range (32 to 126) with Pillow's PCF reader and writes each
glyph as thirteen rows of six bits, which `builtin_font.cpp` expands to the coverage grid an
`ImageGridFont` takes. The header is GENERATED — regenerate it, never edit it.

Pillow and the font file are needed only to regenerate; the committed header needs neither.
"""

import argparse
import gzip
import pathlib

from PIL import PcfFontFile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[3]
OUT = HERE.parent / "src" / "builtin_font_data.h"
FIRST = 32
LAST = 126
WIDTH = 6
HEIGHT = 13
ASCENT = 11

PREAMBLE = """// SPDX-License-Identifier: MIT
#pragma once
// The built-in interface font's glyph rows. GENERATED by src/ui/text/tools/make_builtin_font.py
// from the X Window System's public-domain `misc-fixed` 6x13 font — do not edit by hand.
//
// {count} glyphs, codepoints {first} to {last}, {height} rows each; bit 5 of a row is the leftmost
// of its six pixels.

#include <cy/core/base/types.h>

namespace cy::ui::builtin_font_data {{

inline constexpr u32 kFirstCodepoint = {first};
inline constexpr u32 kGlyphCount = {count};
inline constexpr u32 kCellWidth = {width};
inline constexpr u32 kCellHeight = {height};
inline constexpr u32 kAscent = {ascent};

inline constexpr u8 kRows[kGlyphCount * kCellHeight] = {{
"""


def glyph_rows(font, codepoint: int) -> list[int]:
    entry = font.glyph[codepoint] if codepoint < len(font.glyph) else None
    if entry is None:
        raise SystemExit(f"the font has no glyph for {codepoint}")
    _, _, (x0, y0, x1, y1), image = entry
    if (x1 - x0, y1 - y0) != (WIDTH, HEIGHT) or image is None or image.size != (WIDTH, HEIGHT):
        raise SystemExit(f"glyph {codepoint} is not a {WIDTH}x{HEIGHT} cell")
    rows = []
    for y in range(HEIGHT):
        bits = 0
        for x in range(WIDTH):
            if image.getpixel((x, y)):
                bits |= 1 << (WIDTH - 1 - x)
        rows.append(bits)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pcf", default="/usr/share/fonts/X11/misc/6x13.pcf.gz")
    args = parser.parse_args()
    with gzip.open(args.pcf, "rb") as handle:
        font = PcfFontFile.PcfFontFile(handle)
    count = LAST - FIRST + 1
    body = [PREAMBLE.format(count=count, first=FIRST, last=LAST, width=WIDTH, height=HEIGHT,
                            ascent=ASCENT)]
    for codepoint in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{row:02X}" for row in glyph_rows(font, codepoint))
        shown = {0x20: "space", 0x5C: "backslash"}.get(codepoint, chr(codepoint))
        body.append(f"    {rows},  // {codepoint} {shown}\n")
    body.append("};\n\n}  // namespace cy::ui::builtin_font_data\n")
    OUT.write_text("".join(body), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
