// THE REFERENCE BACKEND, RUNNING A REAL MODEL. M8.c tasks 4.1b and 4.1d.
//
// "SEED MEANS THE BACKEND RUNS, NOT THAT THE INTERFACE COMPILES." This suite loads
// src/ml/assets/threat_classifier.onnx — 637 bytes, committed, generated by
// src/ml/tools/make_threat_classifier.py — through the real ONNX Runtime and checks the numbers
// that come back. An abstraction whose only backend is an interface is a capability nothing
// exercises, which is what M8.b's gate found `audio` to be.
//
// IT IS DECLARED ONLY WHEN `CY_ML_ONNXRUNTIME` IS ON, rather than registered and skipped. A suite
// that reports "passed" while running nothing is the failure mode this project has already paid
// for four times; src/ml/tests/CMakeLists.txt declines to declare it instead.
//
// INTEGRATION, per the taxonomy: it reads a file, builds an ONNX Runtime session, and runs a graph.
// The unit tier's millisecond is for arithmetic.
//
// THE EXPECTED NUMBERS HAVE A PROVENANCE, NOT A HISTORY. Every constant below is printed by the
// generator script from the same weights it writes into the file, so a reader can regenerate both
// and compare. The weights are chosen rather than trained precisely so that this is possible: see
// the script's own header for what each class means.

#include <cy/test/test.h>

#include <cy/core/memory/array.h>
#include <cy/core/memory/system_allocator.h>
#include <cy/ml/backend.h>
#include <cy/ml/schedule.h>
#include <cy/ml/session.h>

#include <cstdio>
#include <cstring>

namespace {

using namespace cy;
using namespace cy::ml;

constexpr const char* kModelPath = CY_ML_TEST_ASSET_DIR "/threat_classifier.onnx";

/// Read the committed model. A plain `std::fopen` rather than the asset system: what is being
/// tested is the backend, and routing through a package would make a failure ambiguous between the
/// two.
[[nodiscard]] Status read_file(const char* path, Array<u8>& bytes) noexcept {
    std::FILE* file = std::fopen(path, "rb");
    if (file == nullptr) {
        return fail(ErrorCode::NotFound, "the committed model asset is not where the test expects");
    }
    u8 buffer[512];
    Status status = ok();
    // `std::feof`/`std::ferror` before every read: a stream whose position is indeterminate after a
    // failed operation is undefined behaviour to keep reading, and this loop would otherwise call
    // `fread` again after a short read for a reason other than the end.
    while (status && std::feof(file) == 0 && std::ferror(file) == 0) {
        const usize read = std::fread(buffer, 1, sizeof(buffer), file);
        if (read == 0) {
            break;
        }
        status = bytes.append(Span<const u8>(buffer, read));
    }
    const bool failed = std::ferror(file) != 0;
    (void)std::fclose(file);
    if (failed) {
        return fail(ErrorCode::Io, "the committed model asset could not be read to its end");
    }
    return status;
}

[[nodiscard]] TensorShape shape_of(std::initializer_list<i64> dimensions) {
    return TensorShape::of(Span<const i64>(dimensions.begin(), dimensions.size())).value();
}

/// The committed model, declared exactly as a cook would declare it.
[[nodiscard]] Expected<ModelAsset, Error> load_asset(Allocator& allocator, Array<u8>& payload,
                                                     bool pinned, const char* device = "cpu") {
    if (Status read = read_file(kModelPath, payload); !read) {
        return make_unexpected(read.error());
    }
    Expected<ModelAsset, Error> asset =
        ModelAsset::create(allocator, Name::intern("perception.threat_classifier"), payload.span());
    if (!asset) {
        return asset;
    }
    TensorSpec features;
    features.name = Name::intern("features");
    features.type = ElementType::F32;
    features.shape = shape_of({TensorShape::kDynamic, 4});

    TensorSpec scores;
    scores.name = Name::intern("scores");
    scores.type = ElementType::F32;
    scores.shape = shape_of({TensorShape::kDynamic, 3});

    if (Status declared = asset.value().declare_input(features); !declared) {
        return make_unexpected(declared.error());
    }
    if (Status declared = asset.value().declare_output(scores); !declared) {
        return make_unexpected(declared.error());
    }
    if (Status declared = asset.value().declare_validated_backend(BackendKind::OnnxRuntime);
        !declared) {
        return make_unexpected(declared.error());
    }
    asset.value().set_precision(Precision::F32);
    if (pinned) {
        ModelDeterminism determinism;
        determinism.backend = BackendKind::OnnxRuntime;
        determinism.precision = Precision::F32;
        determinism.verified_configuration =
            configuration_digest(BackendKind::OnnxRuntime, Precision::F32, device);
        asset.value().set_determinism(determinism);
    }
    return asset;
}

/// The backend, owned for the duration of a case.
class Backend {
public:
    Backend() noexcept : allocator_(system_allocator(MemoryDomain::Engine)) {
        Expected<InferenceBackend*, Error> created = create_onnxruntime_backend(allocator_);
        backend_ = created.has_value() ? created.value() : nullptr;
    }
    ~Backend() { destroy_onnxruntime_backend(backend_, allocator_); }

    Backend(const Backend&) = delete;
    Backend& operator=(const Backend&) = delete;

    [[nodiscard]] InferenceBackend* get() const noexcept { return backend_; }

private:
    Allocator& allocator_;
    InferenceBackend* backend_ = nullptr;
};

[[nodiscard]] usize argmax(Span<const f32> values) noexcept {
    usize best = 0;
    for (usize index = 1; index < values.size(); ++index) {
        if (values[index] > values[best]) {
            best = index;
        }
    }
    return best;
}

CY_TEST_CASE("ml.onnxruntime: this build has the backend and it reports what it can do") {
    CY_CHECK(onnxruntime_compiled_in());

    const Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    CY_CHECK_EQ(backend.get()->kind(), BackendKind::OnnxRuntime);

    const BackendCapabilities capabilities = backend.get()->capabilities();
    CY_CHECK(capabilities.supports(Precision::F32));
    CY_CHECK(capabilities.zero_copy);
    // NOT deterministic, and that is the answer that makes the pinning rule bite: this build
    // dispatches on the instruction set the CPU reports, so two machines are not guaranteed to
    // agree. A backend that claimed determinism here would make `ml-inference`'s boundary vacuous.
    CY_CHECK_FALSE(capabilities.deterministic_execution);
}

CY_TEST_CASE("ml.onnxruntime: the committed model loads and its all-zero answer is the bias") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());
    CY_CHECK_EQ(asset.value().payload().size(), 637U);

    SessionDesc desc;
    desc.max_batch = 4;
    SelectionReport report;
    Expected<InferenceSession, Error> created =
        InferenceSession::create(allocator, registry, asset.value(), desc, report);
    CY_REQUIRE(created.has_value());
    InferenceSession& session = created.value();
    CY_CHECK_EQ(report.outcome, SelectionOutcome::Automatic);
    CY_CHECK_EQ(session.backend(), BackendKind::OnnxRuntime);

    // The all-zero input is the case that can be computed on paper: the hidden layer is Relu(0),
    // so the logits are the output bias [1, -1, -1] and the scores are its softmax —
    // e / (e + 2/e) = 0.786986..., and 0.106507... twice.
    Tensor* input = session.input(0);
    CY_REQUIRE_NE(input, nullptr);
    for (f32& feature : input->as<f32>()) {
        feature = 0.0F;
    }
    CY_REQUIRE(session.run_batch(1).has_value());

    const Span<const f32> scores = session.output(0)->as<const f32>();
    CY_REQUIRE_EQ(scores.size(), 3U);
    CY_CHECK_NEAR(scores[0], 0.786986F, 1e-5F);
    CY_CHECK_NEAR(scores[1], 0.106507F, 1e-5F);
    CY_CHECK_NEAR(scores[2], 0.106507F, 1e-5F);
    // A softmax sums to one, which is the cheapest way to notice a graph that ran the wrong nodes.
    CY_CHECK_NEAR(scores[0] + scores[1] + scores[2], 1.0F, 1e-5F);
    CY_CHECK_GT(session.stats().last_nanoseconds, 0U);
    // Printed so that src/ml/tools/plot_capture.py draws this run rather than a table of its own.
    std::printf("[ml] zero-input %.6f %.6f %.6f\n", static_cast<double>(scores[0]),
                static_cast<double>(scores[1]), static_cast<double>(scores[2]));
}

CY_TEST_CASE("ml.onnxruntime: a batch of agents is one call and each row gets its own class") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());

    SessionDesc desc;
    desc.max_batch = 8;
    SelectionReport report;
    Expected<InferenceSession, Error> created =
        InferenceSession::create(allocator, registry, asset.value(), desc, report);
    CY_REQUIRE(created.has_value());
    InferenceSession& session = created.value();

    // Three agents, one call. proximity, exposure, threat history, ammunition.
    const f32 rows[3][4] = {
        {0.9F, 0.2F, 0.9F, 0.9F},      // close, hidden, hostile, armed  -> engage
        {0.9F, 0.9F, 0.9F, 0.05F},     // close, exposed, hostile, dry   -> retreat
        {0.05F, 0.05F, 0.05F, 0.05F},  // far, calm, unknown, dry        -> ignore
    };
    Span<f32> features = session.input(0)->as<f32>();
    for (usize row = 0; row < 3; ++row) {
        for (usize column = 0; column < 4; ++column) {
            features[(row * 4) + column] = rows[row][column];
        }
    }
    CY_REQUIRE(session.run_batch(3).has_value());
    CY_CHECK_EQ(session.stats().largest_batch, 3U);
    CY_CHECK_EQ(session.stats().invocations, 1U);  // one call, not one per agent

    const Span<const f32> scores = session.output(0)->as<const f32>();
    CY_REQUIRE_EQ(scores.size(), 9U);
    // The argmax of each row, which is a property of the MODEL rather than of one number: a backend
    // that returned the same wrong answer three times would fail here and pass an equality check
    // against a single recorded value.
    CY_CHECK_EQ(argmax(scores.subspan(0, 3)), 1U);  // engage
    CY_CHECK_EQ(argmax(scores.subspan(3, 3)), 2U);  // retreat
    CY_CHECK_EQ(argmax(scores.subspan(6, 3)), 0U);  // ignore
    CY_CHECK_NEAR(scores[0] + scores[1] + scores[2], 1.0F, 1e-5F);
    CY_CHECK_NEAR(scores[3] + scores[4] + scores[5], 1.0F, 1e-5F);
    CY_CHECK_NEAR(scores[6] + scores[7] + scores[8], 1.0F, 1e-5F);
    for (usize row = 0; row < 3; ++row) {
        std::printf("[ml] scores %.6f %.6f %.6f\n", static_cast<double>(scores[(row * 3) + 0]),
                    static_cast<double>(scores[(row * 3) + 1]),
                    static_cast<double>(scores[(row * 3) + 2]));
    }
}

CY_TEST_CASE("ml.onnxruntime: a session runs every tick without allocating again") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());
    SessionDesc desc;
    desc.max_batch = 4;
    SelectionReport report;
    Expected<InferenceSession, Error> created =
        InferenceSession::create(allocator, registry, asset.value(), desc, report);
    CY_REQUIRE(created.has_value());
    InferenceSession& session = created.value();

    Tensor* features = session.input(0);
    Tensor* scores = session.output(0);
    CY_REQUIRE_NE(features, nullptr);
    CY_REQUIRE_NE(scores, nullptr);
    const void* input_address = features->data();
    const void* output_address = scores->data();
    const Span<f32> input_view = features->as<f32>();
    CY_REQUIRE_FALSE(input_view.empty());
    for (u32 tick = 0; tick < 64; ++tick) {
        input_view[0] = static_cast<f32>(tick) / 64.0F;
        CY_REQUIRE(session.run_batch(1).has_value());
    }
    CY_CHECK_EQ(session.stats().invocations, 64U);
    CY_CHECK_EQ(session.stats().allocations, 2U);
    // The tensors ORT read and wrote are the engine's own, in the engine's allocator, and they did
    // not move: that is the zero-copy claim as an address comparison.
    CY_CHECK_EQ(features->data(), input_address);
    CY_CHECK_EQ(scores->data(), output_address);
    std::printf("[ml] onnxruntime mean %llu ns over %llu invocations\n",
                static_cast<unsigned long long>(session.stats().mean_nanoseconds()),
                static_cast<unsigned long long>(session.stats().invocations));
}

CY_TEST_CASE("ml.onnxruntime: the pinning decision follows the asset over a real session") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());
    SessionDesc desc;
    SelectionReport report;

    Array<u8> unpinned_payload(allocator);
    Expected<ModelAsset, Error> unpinned =
        load_asset(allocator, unpinned_payload, /*pinned=*/false);
    CY_REQUIRE(unpinned.has_value());
    Expected<InferenceSession, Error> loose =
        InferenceSession::create(allocator, registry, unpinned.value(), desc, report);
    CY_REQUIRE(loose.has_value());
    CY_CHECK_FALSE(loose.value().is_pinned());

    Array<u8> pinned_payload(allocator);
    Expected<ModelAsset, Error> pinned = load_asset(allocator, pinned_payload, /*pinned=*/true);
    CY_REQUIRE(pinned.has_value());
    Expected<InferenceSession, Error> strict =
        InferenceSession::create(allocator, registry, pinned.value(), desc, report);
    CY_REQUIRE(strict.has_value());
    CY_CHECK(strict.value().is_pinned());

    // Same asset, another device: not pinned, because the digest covers the placement.
    SessionDesc elsewhere;
    elsewhere.device = "cuda:0";
    Expected<InferenceSession, Error> moved =
        InferenceSession::create(allocator, registry, pinned.value(), elsewhere, report);
    CY_REQUIRE(moved.has_value());
    CY_CHECK_FALSE(moved.value().is_pinned());
}

CY_TEST_CASE("ml.onnxruntime: a model the asset misdescribes is refused at session setup") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());
    // A second declared output the model does not have. `ml-inference`'s "WHEN an input tensor's
    // shape does not match the model's declared specification THEN the error SHALL be reported at
    // session setup or first run with both shapes named" — here it is the count, at setup.
    TensorSpec extra;
    extra.name = Name::intern("confidence");
    extra.type = ElementType::F32;
    extra.shape = shape_of({TensorShape::kDynamic, 1});
    CY_REQUIRE(asset.value().declare_output(extra).has_value());

    SessionDesc desc;
    SelectionReport report;
    Expected<InferenceSession, Error> created =
        InferenceSession::create(allocator, registry, asset.value(), desc, report);
    CY_REQUIRE_FALSE(created.has_value());
    CY_CHECK_EQ(created.error().code, ErrorCode::InvalidArgument);
}

CY_TEST_CASE("ml.onnxruntime: cook-time validation accepts this model and refuses a corrupt one") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());
    Array<UnsupportedOperator> unsupported(allocator);
    CY_CHECK(backend.get()->validate(asset.value(), unsupported).has_value());
    CY_CHECK_EQ(unsupported.size(), 0U);

    // Not a model at all. The cook fails with the runtime's own words carried into the report,
    // rather than at first inference on a player's machine.
    static constexpr u8 kRubbish[] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
    Expected<ModelAsset, Error> broken = ModelAsset::create(
        allocator, Name::intern("perception.broken"), Span<const u8>(kRubbish, sizeof(kRubbish)));
    CY_REQUIRE(broken.has_value());
    Status refused = backend.get()->validate(broken.value(), unsupported);
    CY_REQUIRE_FALSE(refused.has_value());
    CY_CHECK_EQ(unsupported.size(), 1U);
    // THE MESSAGE OUTLIVES WHAT PRODUCED IT. `cy::Error::message` does not own its text, and the
    // probe session that generated this one has been destroyed by the time `validate` returns —
    // reading it here is the regression test for a diagnostic that pointed into a dead stack frame
    // and read correctly until something reused it.
    CY_REQUIRE_NE(refused.error().message, nullptr);
    CY_CHECK_GT(std::strlen(refused.error().message), 0U);
    std::printf("[ml] cook refusal: %s\n", refused.error().message);
    std::printf("[ml] cook operator: %s\n", unsupported[0].name);
}

CY_TEST_CASE("ml.onnxruntime: a real model under the frame budget defers rather than overruns") {
    Allocator& allocator = system_allocator(MemoryDomain::Engine);
    Backend backend;
    CY_REQUIRE_NE(backend.get(), nullptr);
    BackendRegistry registry;
    CY_REQUIRE(registry.add(backend.get()).has_value());

    Array<u8> payload(allocator);
    Expected<ModelAsset, Error> asset = load_asset(allocator, payload, /*pinned=*/false);
    CY_REQUIRE(asset.has_value());

    Array<InferenceSession> sessions(allocator);
    CY_REQUIRE(sessions.reserve(6).has_value());
    for (u32 index = 0; index < 6; ++index) {
        SessionDesc desc;
        SelectionReport report;
        Expected<InferenceSession, Error> session =
            InferenceSession::create(allocator, registry, asset.value(), desc, report);
        CY_REQUIRE(session.has_value());
        CY_REQUIRE(sessions.push_back(std::move(session).value()).has_value());
    }

    InferenceScheduler scheduler;
    scheduler.set_budget(InferenceBudget{2, 0});
    scheduler.begin_frame();
    for (usize index = 0; index < sessions.size(); ++index) {
        const InferencePriority priority =
            (index == 5) ? InferencePriority::Critical : InferencePriority::Low;
        CY_REQUIRE(scheduler.submit(sessions[index], priority).has_value());
    }
    CY_REQUIRE(scheduler.dispatch().has_value());
    CY_CHECK_EQ(scheduler.report().dispatched, 2U);
    CY_CHECK_EQ(scheduler.report().deferred, 4U);
    CY_CHECK_EQ(scheduler.pump(), 2U);
    // The critical one ran; four low-priority ones did not. Cost bounded by configuration, over a
    // real runtime rather than over the fake backend.
    CY_CHECK_EQ(sessions[5].stats().invocations, 1U);
    std::printf("[ml] budget %u submitted %u dispatched %u deferred\n",
                scheduler.report().submitted, scheduler.report().dispatched,
                scheduler.report().deferred);
    std::printf("[ml] frame spent %llu ns, utilisation %.2f\n",
                static_cast<unsigned long long>(scheduler.report().nanoseconds_spent),
                static_cast<double>(scheduler.report().utilisation));
}

}  // namespace
