#pragma once
// samples/07-fidelity — the film-detail scene: what it is made of, and how it is cooked.
// M7 tasks 11.1 and 11.2.
//
// ================================================================================================
// EVERY SHELL IS STAR-SHAPED ABOUT ITS OWN ORIGIN, AND THAT IS WHY THE COOK CAN CHECK IT
// ================================================================================================
//
// `virtual-geometry`'s watertightness check reports `closed_source` and only sweeps its cut test on
// a mesh that is closed. A scene whose meshes are open planes and cards would make
// `check_watertight` answer "not applicable" on every asset, and the milestone's own claim — a
// crack-free hierarchy, checked when the asset is COOKED — would be a check that ran and said
// nothing.
//
// So every mesh here is generated by ONE function, `closed_shell`, over a cube-topology grid whose
// vertex is `shape(direction) * direction`: the surface is the graph of a radius over the sphere,
// which is closed by construction whatever the radius does. The five shapes differ only in that
// radius function, and the interesting detail — panelling, fluting, window recesses, a heightfield
// — is all in it.
//
// TWO FACES MUST AGREE ON A SHARED EDGE OR THE WELD HAS NOTHING TO WELD. The grid is emitted per
// face and the seams are welded by position, so the radius is a function of the DIRECTION alone and
// never of the face, the u, or the v. A displacement along the face normal would have been the
// obvious way to write it and would have split every edge of the cube in two.
//
// ================================================================================================
// "MILLIONS OF SOURCE TRIANGLES" IS INSTANCED, AND BOTH NUMBERS ARE REPORTED
// ================================================================================================
//
// A film-detail set is a few hundred thousand triangles of distinct geometry placed a few hundred
// times, which is what virtual geometry is for and what the cook is priced against. So this scene
// reports two figures and never conflates them: `distinct_triangles`, what was cooked, and
// `source_triangles`, what the set contains once every instance is counted. The second is the one
// the milestone's "millions of source triangles" refers to, and the first is the one the cook's
// wall clock is divided by.

#include <cy/core/math/shapes.h>
#include <cy/core/math/vec.h>
#include <cy/core/memory/array.h>
#include <cy/rendering/gi/scene.h>
#include <cy/rendering/gi/system.h>
#include <cy/rendering/virtual_geometry/asset.h>
#include <cy/rendering/virtual_geometry/build.h>
#include <cy/rendering/virtual_geometry/traversal.h>

namespace cy::sample::fidelity {

/// One generated mesh, in the form `vg::build_geometry` reads.
struct Mesh {
    explicit Mesh(Allocator& allocator) noexcept
        : positions(allocator), normals(allocator), uvs(allocator), indices(allocator) {}

    Array<Vec3> positions;
    Array<Vec3> normals;
    Array<Vec2> uvs;
    Array<u32> indices;

    [[nodiscard]] rendering::vg::SourceMesh source() const noexcept;
    [[nodiscard]] u32 triangles() const noexcept { return static_cast<u32>(indices.size() / 3U); }
};

/// Which shell a piece of the set is. The radius function is selected by this and nothing else.
enum class Shape : u8 {
    /// The interior: a panelled room, generated as the solid whose inside is the room.
    Hall = 0,
    /// A fluted column. The interior's repeated detail.
    Column,
    /// A displaced boulder. The interior's and the exterior's sculpted detail.
    Statue,
    /// An exterior facade block, with window recesses cut by the radius.
    Facade,
    /// An exterior ground slab carrying a heightfield.
    Terrain,
    Count,
};

[[nodiscard]] const char* shape_name(Shape shape) noexcept;

/// Generate one shell. `resolution` is the number of quads along one edge of one cube face, so the
/// mesh carries `12 * resolution^2` triangles.
[[nodiscard]] Status generate(Shape shape, u32 resolution, Mesh& out) noexcept;

/// One cooked asset and what the cook reported about it.
struct CookedAsset {
    explicit CookedAsset(Allocator& allocator) noexcept : bytes(allocator) {}

    Shape shape = Shape::Hall;
    Array<u8> bytes;
    u32 source_triangles = 0;
    u32 clusters = 0;
    u32 levels = 0;
    u32 pages = 0;
    u32 resident_bytes = 0;
    u32 cooked_bytes = 0;
    f32 cook_ms = 0.0F;
    rendering::vg::WatertightReport watertight{};
};

/// How much of the set to build. The defaults are the artefact's; the smoke entry lowers them.
struct SceneOptions {
    /// Quads per cube-face edge, per shape. The cook's cost is superlinear in this, so it is the
    /// one dial the smoke entry turns down.
    u32 resolution[static_cast<u32>(Shape::Count)] = {40, 40, 48, 44, 48};
    /// Instances placed, per shape. The interior is one hall.
    u32 instances[static_cast<u32>(Shape::Count)] = {1, 40, 24, 72, 49};
};

/// The whole set: the cooked assets, the instances placed over them, and the totals.
struct Scene {
    explicit Scene(Allocator& arena) noexcept
        : allocator(arena),
          assets(arena),
          decoded(arena),
          instances(arena),
          surfels(arena),
          lights(arena) {}

    Allocator& allocator;
    Array<CookedAsset> assets;
    Array<rendering::vg::DecodedAsset> decoded;
    Array<rendering::vg::GeometryInstance> instances;
    Array<rendering::gi::Surfel> surfels;
    Array<rendering::gi::GiLight> lights;

    Aabb bounds{};
    u64 source_triangles = 0;
    u32 distinct_triangles = 0;
    u32 clusters = 0;
    u32 pages = 0;
    u64 cooked_bytes = 0;
    u64 resident_bytes = 0;
    f32 cook_ms = 0.0F;
    /// Assets whose source mesh was closed and whose hierarchy passed the crack-free check.
    u32 watertight_assets = 0;
    u32 closed_assets = 0;
};

/// Build and cook the whole set. Every figure in `Scene` is filled in here.
[[nodiscard]] Status build_scene(const SceneOptions& options, Scene& out) noexcept;

/// The camera path: a shot that starts inside the hall and ends outside it, so one run sees both
/// halves of "a film-detail interior and exterior".
[[nodiscard]] Vec3 camera_at(const Scene& scene, f32 t) noexcept;
[[nodiscard]] Vec3 camera_target(const Scene& scene, f32 t) noexcept;

}  // namespace cy::sample::fidelity
