#pragma once
// Build-time feature slicing, as something a program can state rather than assume. Task 4.1.4.
//
// `engine-architecture` — "Build-time feature slicing": whole subsystems are compiled out through
// CMake options, each defining a guard macro. And its "Dedicated server build" scenario: with
// rendering, audio, UI and the editor disabled, "the binary SHALL link no graphics or audio
// backend, and the render and audio servers SHALL be null implementations that preserve handle
// semantics".
//
// --- WHAT THIS FILE ADDS TO cy_features.h --------------------------------------------------------
//
// `<cy_features.h>` is generated by cmake/features.cmake and is a list of macros. A macro is
// invisible to everything but the preprocessor: it cannot be logged, cannot be written into a crash
// artefact, cannot be compared against what a save file was written by, and cannot be asserted on
// by a test without that test restating the macro and thereby testing itself.
//
// This file turns the macros into **data, once**, at the one place they are read. Everything
// downstream — the startup log, the trace metadata, the smoke test that a dedicated server build
// really excluded the renderer — reads the table instead of the preprocessor, so there is exactly
// one `#if` per feature in the engine and it is here.
//
// The table is generated from `CY_FEATURE_TABLE`, which the generator already emits for exactly
// this purpose, so adding a feature to cmake/features.cmake adds it here with no edit at all. That
// is why `feature_count()` is not a constant written down twice.
//
// --- THE SEAM THAT IS STILL EMPTY ----------------------------------------------------------------
//
// `CY_DEDICATED_SERVER` is a top-level CMake option and is *not* in the generated feature table —
// it is orthogonal to the configuration, and the link-set check that gives it teeth is the
// top-level `cy_check_dedicated_server_link()`, still an M0 stub because no client-only target
// exists to exclude until the renderer lands at M3. `dedicated_server()` below reports the macro so
// that the runtime's report is complete; it is not evidence that anything was excluded, and the
// comment says so rather than letting the accessor imply it.

#include <cy/core/base/types.h>
#include <cy/core/memory/array.h>

namespace cy::runtime {

/// One row of the build's feature table.
struct FeatureState {
    const char* name = "";
    bool enabled = false;
};

/// Every feature the build declared, enabled or not, in the generator's order (alphabetical, and
/// therefore stable). Never empty.
[[nodiscard]] Span<const FeatureState> features() noexcept;

/// The state of one feature by name, or false when the build declares no such feature.
///
/// `found` distinguishes "declared and off" from "not a feature of this build" — a caller asking
/// about `CY_TYPO` should learn that it asked the wrong question rather than that the answer is no.
[[nodiscard]] bool feature_enabled(const char* name, bool* found = nullptr) noexcept;

/// Compiled with `-DCY_DEDICATED_SERVER=1`. Reports the macro and nothing more; see the header
/// comment on why that is not yet the same as "no client-only target is linked".
[[nodiscard]] constexpr bool dedicated_server() noexcept {
#if defined(CY_DEDICATED_SERVER)
    return true;
#else
    return false;
#endif
}

/// Assertions and development-only diagnostics are compiled in. The `debug` and `dev` profiles;
/// false in `profile` and `release`.
///
/// Present because a test that asserts on assertion behaviour has to know, and M0's suite went red
/// in two profiles for not knowing. Nothing should branch on it to *change* behaviour.
[[nodiscard]] constexpr bool development_build() noexcept {
#if defined(CY_DEVELOPMENT)
    return true;
#else
    return false;
#endif
}

}  // namespace cy::runtime
