// samples/10-world — M10's artefact: seven modules, one world, one day.
//
// ================================================================================================
// WHAT THIS PROGRAM CLAIMS, AND WHAT IT DOES NOT
// ================================================================================================
//
// IT CLAIMS: a 1 536 m world is GENERATED by `cy::pcg` over a nine-node graph carrying the three
// kinds of edge M10's spike measured, under the four conditions that spike made binding; its
// elevation raster is COOKED into `cy::terrain` tiles at three levels, the coarse ones decimated
// from the fine; `cy::water` floats a spectral ocean on it and publishes depth, distance, flow and
// shore wetness into `cy::environment`; `cy::weather` runs a climate over the terrain's own
// elevation and publishes wind, temperature, precipitation, wetness and snow into the same
// substrate; `cy::foliage` reads that substrate and terrain's surface back out to place tens of
// thousands of plants, and reads the wind field to move them; and `cy::rendering::sky` composes the
// atmosphere, the volumetric cloud deck weather drives, and the light everything is shaded by.
// Every module writes into or reads out of `cy::environment` and NONE of them links another.
//
// SINCE M11.c IT ALSO CLAIMS THE ENGINE'S OWN FRAME, and that sentence is narrower than it sounds.
// The picture is assembled by `cy::rendering::assembly::FrameAssembly` — the post chain decides the
// feature set, the temporal framework advances a PINNED jitter, the shadow cache spends its budget,
// the sky table updates, and the stages go into the render graph in the specification's order —
// and it is resolved by `cy::rendering-pipeline`'s tonemapping pass at the exposure
// `samples/10-world/frame.cypost` commits. The stage list the frame ran is written beside the still
// as `<still>.manifest.txt`, so a caption claiming a stage is a claim something can check.
//
// IT STILL DOES NOT CLAIM the engine's own forward SHADING. Every producer above runs on the
// PROCESSOR, this program's geometry is its own rather than the render server's mesh table, and the
// colour it draws is per-vertex colour those producers computed. There is no terrain material page
// bound on a device, no environment field sampled through its GPU image, no water surface published
// into the GPU scene, no grass expanded on the device and no cloud marched per pixel — six of M10's
// modules each recorded exactly that gap against their own row, and this artefact closes none of
// them. AND THERE IS NO ANTI-ALIASING: nothing in this tree records `FramePassKind::Temporal`, so
// the chain this frame runs is exposure, tone mapping and output encoding, and the manifest says
// three. README.md says so, the report below says so, and the video's caption says so.
//
// ================================================================================================
// THE TIMESTEP IS FIXED, AND THAT IS A REPRODUCIBILITY CLAIM
// ================================================================================================
//
// One frame is one simulated tick of every module in the world, and a take is exactly one simulated
// day. There is no wall clock anywhere in the loop, so two runs of this program produce the same
// world at the same frame index — which is what makes the video a thing a reviewer can regenerate
// and compare rather than a recording of one afternoon. It is the same argument
// samples/09b-animated-character makes, and the same one `simulation-and-determinism` makes about a
// simulation tick.

#include "stage.h"
#include "world.h"

#include <cy/core/memory/system_allocator.h>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>

namespace {

using namespace cy;
using namespace cy::sample::world;

struct Options {
    std::string frames;
    std::string still;
    std::string budget;
    /// Where the committed grade lives. M11.c task 3.3: a path rather than a constant, so a person
    /// grading the shot edits a file. Defaults to the one this sample ships.
    std::string grade = "samples/10-world/frame.cypost";
    /// 960x540 AND NOT 720p, AND THE REASON IS THE COMMITTED VIDEO RATHER THAN THE PICTURE. This
    /// default is what `just capture-world` writes into `docs/design/videos/`, and a forest of a
    /// hundred thousand small triangles is the hardest thing x264 is ever asked to carry: the same
    /// day at 1280x720 encodes to 9.0 MiB at the CRF `tools/docs/collect_world.py` picked, against
    /// 5.0 MiB here, and that file has to be cloned by everyone who clones the repository. The
    /// budget table in this sample's README is measured at this resolution too — the frame cost is
    /// dominated by per-vertex work on the processor and barely moves with it (123.41 ms mean at
    /// 720p against 123 ms here), but a table and a picture that disagree about their own capture
    /// would still be two claims. `--width`/`--height` override both.
    u32 width = 960;
    u32 height = 540;
    u32 fps = 30;
    /// Which frame is written a second time under `--still`. Chosen by `--still-frame`, and
    /// defaulted to just over a quarter of the way through the take — mid-morning, before the front
    /// arrives, with the sun high enough for the terrain's relief and the forest to read and low
    /// enough to cast shape into the hills. It is the run's most legible frame and not a second
    /// claim; the video is where every other hour of the day is.
    u32 still_frame = 0;
    u32 regions = 24;
    u64 seed = WorldOptions{}.seed;
    f32 seconds = 24.0F;
    /// The frame budget this run is JUDGED against, in milliseconds, or zero for "report only".
    ///
    /// WHY THE ASSERTION IS IN THE PROGRAM AND NOT IN THE LEDGER THAT CALLS IT. `m10:world-frame-
    /// budget` runs this binary by absolute path, writes a CSV and judges the CSV in Python; the
    /// two M11.a criteria that replace it were written as `just run-sample ... --budget-ms 16.7`
    /// and neither the sample name nor the flag existed, so BOTH EXITED 2 — "no sample '10-world'"
    /// — on every machine, and `roadmap-falsify` recorded that exit as "red against a built tree",
    /// which is what a criterion that is red because its subject failed also records. A check that
    /// cannot run is not distinguishable from a check that ran and failed, which is this project's
    /// seven-times defect one level up. The flag exists so the two are different runs.
    f32 budget_ms = 0.0F;
    bool headless = false;
};

/// `strtol` and `strtoull` rather than `atoi`, which reports no conversion error at all: a
/// `--fps banana` would silently become zero and the run would divide by it.
[[nodiscard]] bool read_u32(const char* text, u32& out) noexcept {
    char* end = nullptr;
    const long value = std::strtol(text, &end, 10);
    if (end == text || *end != '\0' || value <= 0) {
        return false;
    }
    out = static_cast<u32>(value);
    return true;
}

[[nodiscard]] bool read_u64(const char* text, u64& out) noexcept {
    char* end = nullptr;
    const unsigned long long value = std::strtoull(text, &end, 0);
    if (end == text || *end != '\0') {
        return false;
    }
    out = static_cast<u64>(value);
    return true;
}

[[nodiscard]] bool read_f32(const char* text, f32& out) noexcept {
    char* end = nullptr;
    const double value = std::strtod(text, &end);
    if (end == text || *end != '\0' || value <= 0.0) {
        return false;
    }
    out = static_cast<f32>(value);
    return true;
}

/// One pass over the command line, with "did this flag match, and did its value parse" answered in
/// one place. Nine copies of the same four lines is where the ninth quietly forgets the third —
/// samples/09b-animated-character's own argument, and the same cursor.
class Cursor {
public:
    Cursor(int argc, char** argv) noexcept : argc_(argc), argv_(argv) {}

    [[nodiscard]] bool advance() noexcept { return ++index_ < argc_; }
    [[nodiscard]] std::string_view current() const noexcept { return argv_[index_]; }
    [[nodiscard]] bool failed() const noexcept { return failed_; }

    [[nodiscard]] bool flag(std::string_view name, bool& out) const noexcept {
        if (current() != name) {
            return false;
        }
        out = true;
        return true;
    }

    [[nodiscard]] bool text(std::string_view name, std::string& out) noexcept {
        const char* value = value_for(name);
        if (value == nullptr) {
            return matched_;
        }
        out = value;
        return true;
    }

    [[nodiscard]] bool number(std::string_view name, u32& out) noexcept {
        const char* value = value_for(name);
        if (value == nullptr) {
            return matched_;
        }
        failed_ = failed_ || !read_u32(value, out);
        return true;
    }

    [[nodiscard]] bool number(std::string_view name, u64& out) noexcept {
        const char* value = value_for(name);
        if (value == nullptr) {
            return matched_;
        }
        failed_ = failed_ || !read_u64(value, out);
        return true;
    }

    [[nodiscard]] bool number(std::string_view name, f32& out) noexcept {
        const char* value = value_for(name);
        if (value == nullptr) {
            return matched_;
        }
        failed_ = failed_ || !read_f32(value, out);
        return true;
    }

private:
    /// The value after `name`, or null. `matched_` separates "this was not the flag" from "it was
    /// the flag and it had no value", which the callers above return as a match so the next flag is
    /// not also tried against it.
    [[nodiscard]] const char* value_for(std::string_view name) noexcept {
        matched_ = false;
        if (current() != name) {
            return nullptr;
        }
        matched_ = true;
        if (index_ + 1 >= argc_) {
            failed_ = true;
            return nullptr;
        }
        return argv_[++index_];
    }

    int argc_ = 0;
    char** argv_ = nullptr;
    int index_ = 0;
    bool matched_ = false;
    bool failed_ = false;
};

[[nodiscard]] bool parse(int argc, char** argv, Options& out) noexcept {
    Cursor cursor(argc, argv);
    while (cursor.advance()) {
        const bool recognised =
            cursor.text("--frames", out.frames) || cursor.text("--still", out.still) ||
            cursor.text("--grade", out.grade) || cursor.text("--budget", out.budget) ||
            cursor.number("--width", out.width) || cursor.number("--height", out.height) ||
            cursor.number("--fps", out.fps) || cursor.number("--still-frame", out.still_frame) ||
            cursor.number("--regions", out.regions) || cursor.number("--seed", out.seed) ||
            cursor.number("--seconds", out.seconds) ||
            cursor.number("--budget-ms", out.budget_ms) || cursor.flag("--headless", out.headless);
        if (!recognised) {
            const std::string_view argument = cursor.current();
            std::fprintf(stderr, "unknown argument: %.*s\n", static_cast<int>(argument.size()),
                         argument.data());
            return false;
        }
        if (cursor.failed()) {
            const std::string_view argument = cursor.current();
            std::fprintf(stderr, "bad value for %.*s\n", static_cast<int>(argument.size()),
                         argument.data());
            return false;
        }
    }
    // An odd dimension is refused HERE, at the earliest of the two places that could: the video
    // encoder's yuv420p needs even dimensions, and refusing at the argument is one place to enforce
    // it rather than a filter in the collector that silently rescales the picture.
    if ((out.width % 2) != 0 || (out.height % 2) != 0) {
        std::fprintf(stderr, "--width and --height must be even, for the video encoder's 4:2:0\n");
        return false;
    }
    return true;
}

void print_build_report(const BuildReport& report) {
    std::printf("\n=== the world, as its producers reported it ===\n");
    std::printf("  pcg      %u regions, %llu region-evaluations over %u stages, %llu points\n",
                report.pcg_regions, static_cast<unsigned long long>(report.pcg_region_evaluations),
                report.pcg_stages, static_cast<unsigned long long>(report.pcg_points));
    std::printf(
        "           %llu of those points became boulders in %u foliage clusters through "
        "pcg::FoliageOutputAdapter — no entities\n",
        static_cast<unsigned long long>(report.pcg_boulders), report.pcg_boulder_clusters);
    std::printf("           program digest 0x%016llX, cacheable %s, %.0f ms\n",
                static_cast<unsigned long long>(report.program_digest),
                report.pcg_cacheable ? "yes"
                                     : "no (budgeted, and the spike says a budgeted result "
                                       "is not cacheable)",
                report.pcg_millis);
    std::printf("  terrain  %u tiles over 3 levels, %llu bytes resident, %u triangles meshed\n",
                report.terrain_tiles, static_cast<unsigned long long>(report.terrain_bytes),
                report.terrain_triangles);
    std::printf(
        "           elevation %.1f m to %.1f m, %u vertices stitched to a coarser "
        "neighbour, %.0f ms\n",
        static_cast<double>(report.terrain_min_height),
        static_cast<double>(report.terrain_max_height), report.terrain_stitched_vertices,
        report.terrain_millis);
    std::printf(
        "  water    significant height %.2f m, peak wavelength %.1f m, %u cascades "
        "(%u authoritative + %u visual-only)\n",
        static_cast<double>(report.sea_significant_height),
        static_cast<double>(report.sea_peak_wavelength), report.sea_cascades,
        report.sea_authoritative_bands, report.sea_visual_bands);
    std::printf(
        "  foliage  %llu instances in %u clusters of %u species, %llu bytes "
        "(%.1f bytes an instance), %.0f ms\n",
        static_cast<unsigned long long>(report.foliage_instances), report.foliage_clusters,
        report.foliage_species, static_cast<unsigned long long>(report.foliage_bytes),
        report.foliage_instances == 0 ? 0.0
                                      : static_cast<double>(report.foliage_bytes) /
                                            static_cast<double>(report.foliage_instances),
        report.foliage_millis);
    std::printf(
        "  fields   %u declared, %u claimed by four different producers, %llu bytes "
        "resident\n",
        report.fields_declared, report.fields_claimed,
        static_cast<unsigned long long>(report.field_bytes));
    std::printf("  sky      %llu directions integrated into the atmosphere tables, %.0f ms\n",
                static_cast<unsigned long long>(report.sky_directions_integrated),
                report.sky_tables_millis);
}

void print_persistence(const World::PersistenceReport& report) {
    std::printf("\n=== m10 task 7.2: a crater that survives a save ===\n");
    std::printf("  the gameplay surface dropped %.2f m where the crater was stamped\n",
                static_cast<double>(report.depth_before));
    std::printf(
        "  recorded into world::PersistenceOverlay as %u subsystem blob(s) over %u cell(s),"
        " %llu bytes\n",
        report.overlay_blobs, report.overlay_cells,
        static_cast<unsigned long long>(report.overlay_bytes));
    std::printf("  the delta store was cleared (the crater verified gone), then restored: %s\n",
                report.restored ? "restored" : "NOTHING CAME BACK");
    std::printf(
        "  the surface is %.2f m down again, and %u of %u probes over the crater "
        "disagree with the pre-save surface\n",
        static_cast<double>(report.depth_after_restore), report.samples_disagreeing,
        report.samples_compared);
}

/// The budget curve M10 tasks.md 7.3 asks for: every frame of the cycle, per producer, in
/// milliseconds. A CSV rather than a summary, because "measured as a curve across the cycle rather
/// than asserted at one time of day" is a request for every point and not for a maximum.
[[nodiscard]] bool write_budget(const std::string& path, const Array<FrameCosts>& costs,
                                const Array<f32>& day, const Array<f32>& sun_elevation,
                                const Array<f32>& rain, const Array<StageReport>& stage) {
    std::FILE* file = std::fopen(path.c_str(), "w");
    if (file == nullptr) {
        std::fprintf(stderr, "could not write the budget curve to %s\n", path.c_str());
        return false;
    }
    std::fprintf(file,
                 "frame,day_fraction,sun_elevation_degrees,precipitation_mm_per_hour,weather_ms,"
                 "water_ms,ocean_ms,sky_ms,terrain_shade_ms,foliage_ms,producers_ms,"
                 "stage_build_ms,stage_submit_ms,frame_ms,field_points,field_throttled,"
                 "plants_drawn,stars_drawn,triangles\n");
    for (usize frame = 0; frame < costs.size(); ++frame) {
        const FrameCosts& cost = costs[frame];
        const StageReport& drawn = stage[frame];
        const f64 total = cost.total() + drawn.build_ms + drawn.submit_ms;
        std::fprintf(
            file,
            "%llu,%.6f,%.3f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%llu,%u,%u,%u,"
            "%u\n",
            static_cast<unsigned long long>(frame), static_cast<double>(day[frame]),
            static_cast<double>(sun_elevation[frame]), static_cast<double>(rain[frame]),
            cost.weather_ms, cost.water_ms, cost.ocean_ms, cost.sky_ms, cost.terrain_shade_ms,
            cost.foliage_ms, cost.total(), drawn.build_ms, drawn.submit_ms, total,
            static_cast<unsigned long long>(cost.field_points),
            cost.field_publication_throttled ? 1U : 0U, drawn.plants_drawn, drawn.stars_drawn,
            drawn.sky_triangles + drawn.terrain_triangles + drawn.water_triangles +
                drawn.foliage_triangles);
    }
    (void)std::fclose(file);
    return true;
}

/// Everything the take collects, frame by frame. A struct rather than six parallel arrays passed
/// through three functions, because six parallel arrays is where the seventh gets forgotten.
struct Take {
    explicit Take(Allocator& allocator) noexcept
        : costs(allocator), drawn(allocator), sun(allocator), rain(allocator), day(allocator) {}

    Take(const Take&) = delete;
    Take& operator=(const Take&) = delete;

    Array<FrameCosts> costs;
    Array<StageReport> drawn;
    Array<f32> sun;
    Array<f32> rain;
    Array<f32> day;
    u32 validation_errors = 0;
};

[[nodiscard]] bool record_frame(Take& take, const WorldState& state, const FrameCosts& cost,
                                const StageReport& stage) {
    return take.costs.push_back(cost) && take.drawn.push_back(stage) &&
           take.sun.push_back(state.sun_elevation_degrees) &&
           take.rain.push_back(state.precipitation_mm_per_hour) &&
           take.day.push_back(state.day_fraction);
}

/// A line every simulated hour of the take, so a run that is going wrong says so while it is going
/// wrong rather than at the end.
void print_hour(u64 frame, const WorldState& state) {
    std::printf(
        "  %5llu  %02.0f:%02.0f  sun %+6.1f deg  %5.1f C  wind %4.1f m/s  "
        "%s %4.1f mm/h  cloud %.2f sun-t %.2f thickest %.2f  wet %.2f  "
        "snow %.3f/%.3f m  sky %10.5f nit  star %.2f\n",
        static_cast<unsigned long long>(frame),
        std::floor(static_cast<double>(state.day_fraction) * 24.0),
        std::floor(std::fmod(static_cast<double>(state.day_fraction) * 1440.0, 60.0)),
        static_cast<double>(state.sun_elevation_degrees),
        static_cast<double>(state.temperature_celsius), static_cast<double>(state.wind_speed_mps),
        state.precipitation, static_cast<double>(state.precipitation_mm_per_hour),
        static_cast<double>(state.cloud_coverage), static_cast<double>(state.cloud_transmittance),
        static_cast<double>(state.thickest_cloud), static_cast<double>(state.wetness),
        static_cast<double>(state.snow_depth_metres),
        static_cast<double>(state.snow_depth_west_metres), static_cast<double>(state.mean_sky_nits),
        static_cast<double>(state.star_visibility));
}

/// One frame's picture, and the still when this is the still's frame. Separated from the loop
/// because "draw, and maybe draw again" is the only thing in it that can fail two ways.
[[nodiscard]] Status shoot_frame(Stage& stage, const World& world, const Options& options,
                                 u64 frame, u64 frames, u32 still_frame, StageReport& out) {
    WorldVec3d eye;
    WorldVec3d target;
    world.camera_at(frame, frames, eye, target);
    char path[512];
    std::snprintf(path, sizeof(path), "%s/frame_%04llu.png", options.frames.c_str(),
                  static_cast<unsigned long long>(frame));
    if (Status shot = stage.shoot(world, eye, target, path, out); !shot) {
        return shot;
    }
    if (frame != still_frame || options.still.empty()) {
        return ok();
    }
    if (Status shot = stage.shoot(world, eye, target, options.still.c_str(), out); !shot) {
        return shot;
    }
    // THE STILL IS PUBLISHED WITH THE FRAME'S OWN STAGE LIST BESIDE IT. M11.c task 3.2, and
    // `rendering-post-processing`'s new requirement in as many words: "a published capture SHALL be
    // accompanied by that stage list, and where a caption states that a stage ran, the statement
    // SHALL be checkable against it". The manifest is emitted by the frame — every line of it comes
    // off `AssemblyReport` — so a caption claiming a stage this frame did not run is a check that
    // fails rather than a sentence a reader has to take on trust.
    char manifest_path[600];
    std::snprintf(manifest_path, sizeof(manifest_path), "%s.manifest.txt", options.still.c_str());
    return stage.write_manifest(out, manifest_path);
}

/// Simulate and film the whole cycle.
[[nodiscard]] Status run_take(World& world, Stage& stage, const Options& options, u64 frames,
                              u32 still_frame, bool wants_pictures, Take& take) {
    for (u64 frame = 0; frame < frames; ++frame) {
        FrameCosts cost;
        if (Status advanced = world.advance(cost); !advanced) {
            return advanced;
        }
        StageReport stage_report;
        if (wants_pictures) {
            if (Status shot =
                    shoot_frame(stage, world, options, frame, frames, still_frame, stage_report);
                !shot) {
                return shot;
            }
            take.validation_errors = stage_report.validation_errors;
        }
        if (!record_frame(take, world.state(), cost, stage_report)) {
            return fail(ErrorCode::OutOfMemory, "the take did not record a frame");
        }
        if ((frame % (frames / 24 == 0 ? 1 : frames / 24)) == 0) {
            print_hour(frame, world.state());
        }
    }
    return ok();
}

/// The three numbers a reader wants from the curve, and where the worst frame was.
void print_budget(const Take& take) {
    f64 worst = 0.0;
    f64 best = 1e30;
    f64 mean = 0.0;
    usize worst_frame = 0;
    for (usize frame = 0; frame < take.costs.size(); ++frame) {
        const f64 total =
            take.costs[frame].total() + take.drawn[frame].build_ms + take.drawn[frame].submit_ms;
        mean += total;
        if (total > worst) {
            worst = total;
            worst_frame = frame;
        }
        best = total < best ? total : best;
    }
    mean /= take.costs.empty() ? 1.0 : static_cast<f64>(take.costs.size());
    std::printf("\n=== m10 task 7.3: the frame budget across a full day/night cycle ===\n");
    std::printf("  %.2f ms best, %.2f ms mean, %.2f ms worst (frame %llu, sun %+.1f deg)\n", best,
                mean, worst, static_cast<unsigned long long>(worst_frame),
                take.sun.empty() ? 0.0 : static_cast<double>(take.sun[worst_frame]));
    // A BUDGET HELD BY DROPPING WORK IS NOT A BUDGET HELD, so the one lever in this world that
    // actually throttles says so on its own line rather than only in a column. Weather defers a
    // field publication whose lattice would exceed the tick's allowance, and a frame that published
    // nothing is a frame whose consumers read the previous tick's weather.
    cy::u64 throttled = 0;
    cy::u64 points = 0;
    for (const FrameCosts& cost : take.costs) {
        throttled += cost.field_publication_throttled ? 1U : 0U;
        points += cost.field_points;
    }
    std::printf(
        "  substrate: %llu lattice point(s) published a frame, %llu frame(s) deferred by "
        "the field-update budget\n",
        static_cast<unsigned long long>(take.costs.empty() ? 0 : points / take.costs.size()),
        static_cast<unsigned long long>(throttled));
    std::printf("  the whole curve is in the CSV; the video's companion figure plots it.\n");
}

/// The mean of every band of the take, largest first, and the frame that was worst.
///
/// `producers_ms` is deliberately NOT a band: it is the SUM of six of the ones below it, so a table
/// that included it would report the total as the largest band and say nothing about where the time
/// goes. `m10:world-frame-budget`'s own Python excludes it for the same reason, and this function
/// exists so the two presentations are one implementation rather than two that can drift.
struct Band {
    const char* name;
    f64 mean_ms;
};

/// JUDGE the take against a budget. Returns false when the worst frame is over it.
///
/// THE WORST FRAME AND NOT THE MEAN, because a budget a frame misses is a frame that stutters, and
/// a mean inside 16.7 ms with a worst at 40 is a scene that hitches once a second.
/// `m10:world-frame- budget` judges the worst for the same reason and this reproduces its
/// arithmetic.
[[nodiscard]] bool judge_budget(const Take& take, f32 budget_ms) {
    if (take.costs.empty()) {
        std::fprintf(stderr,
                     "--budget-ms was given and the take recorded no frame at all, so there is "
                     "nothing to judge: a budget held over zero frames is the emptiest false "
                     "green there is\n");
        return false;
    }
    const auto frames = static_cast<f64>(take.costs.size());
    f64 worst = 0.0;
    f64 mean = 0.0;
    usize worst_frame = 0;
    Band bands[] = {{"weather_ms", 0.0},     {"water_ms", 0.0},         {"ocean_ms", 0.0},
                    {"sky_ms", 0.0},         {"terrain_shade_ms", 0.0}, {"foliage_ms", 0.0},
                    {"stage_build_ms", 0.0}, {"stage_submit_ms", 0.0}};
    for (usize frame = 0; frame < take.costs.size(); ++frame) {
        const FrameCosts& cost = take.costs[frame];
        const StageReport& drawn = take.drawn[frame];
        const f64 total = cost.total() + drawn.build_ms + drawn.submit_ms;
        mean += total;
        if (total > worst) {
            worst = total;
            worst_frame = frame;
        }
        bands[0].mean_ms += cost.weather_ms;
        bands[1].mean_ms += cost.water_ms;
        bands[2].mean_ms += cost.ocean_ms;
        bands[3].mean_ms += cost.sky_ms;
        bands[4].mean_ms += cost.terrain_shade_ms;
        bands[5].mean_ms += cost.foliage_ms;
        bands[6].mean_ms += drawn.build_ms;
        bands[7].mean_ms += drawn.submit_ms;
    }
    mean /= frames;
    for (Band& band : bands) {
        band.mean_ms /= frames;
    }
    const usize count = sizeof(bands) / sizeof(bands[0]);
    for (usize outer = 0; outer + 1 < count; ++outer) {
        for (usize inner = 0; inner + 1 < count - outer; ++inner) {
            if (bands[inner + 1].mean_ms > bands[inner].mean_ms) {
                const Band held = bands[inner];
                bands[inner] = bands[inner + 1];
                bands[inner + 1] = held;
            }
        }
    }
    std::printf("\n=== judged against a %.1f ms budget ===\n", static_cast<double>(budget_ms));
    std::printf(
        "  %llu frames: %.1f ms mean, %.1f ms worst (frame %llu), %.1fx the budget at the "
        "worst frame\n",
        static_cast<unsigned long long>(take.costs.size()), mean, worst,
        static_cast<unsigned long long>(worst_frame), worst / static_cast<f64>(budget_ms));
    std::printf("  the three largest bands: %s %.1f ms, %s %.1f ms, %s %.1f ms\n", bands[0].name,
                bands[0].mean_ms, bands[1].name, bands[1].mean_ms, bands[2].name, bands[2].mean_ms);
    if (worst <= static_cast<f64>(budget_ms)) {
        std::printf("  INSIDE the budget at every frame of the cycle.\n");
        return true;
    }
    std::fprintf(stderr,
                 "  OVER the budget: the worst frame of the cycle costs %.1f ms against %.1f ms.\n",
                 worst, static_cast<double>(budget_ms));
    return false;
}

/// Open the device and upload what never changes. Absent-device is SUCCESS with `available()`
/// false, and the caller decides what that means.
[[nodiscard]] Status open_stage(Stage& stage, const World& world, const Options& options) {
    // THE GRADE IS READ BEFORE THE DEVICE IS OPENED, and a missing file stops the run. M11.c task
    // 3.3: the exposure this shot is tuned at is content — `samples/10-world/frame.cypost` — and a
    // program that fell back to a default when it could not find it would photograph an ungraded
    // shot and report a graded one.
    if (Status graded = stage.read_grade(options.grade.c_str()); !graded) {
        std::fprintf(stderr, "the committed grade '%s' could not be read: %s\n",
                     options.grade.c_str(), graded.error().message);
        return graded;
    }
    if (Status opened = stage.open(options.width, options.height); !opened) {
        return opened;
    }
    if (!stage.available()) {
        return ok();
    }
    return stage.stage_world(world);
}

}  // namespace

int main(int argc, char** argv) {
    Options options;
    if (!parse(argc, argv, options)) {
        return 2;
    }

    Allocator& allocator = system_allocator(MemoryDomain::World);
    WorldOptions world_options;
    world_options.seed = options.seed;
    world_options.region_edge = static_cast<i32>(options.regions);
    world_options.foliage_edge = static_cast<i32>(options.regions);
    world_options.seconds_per_day = options.seconds;
    world_options.take_fps = static_cast<f32>(options.fps);

    World world(allocator, world_options);
    BuildReport report;
    const auto began = std::chrono::steady_clock::now();
    if (Status built = world.build(report); !built) {
        std::fprintf(stderr, "the world did not build: %s\n", built.error().message);
        return 1;
    }
    const auto finished = std::chrono::steady_clock::now();
    print_build_report(report);
    std::printf("  total    %.0f ms to generate, cook, claim and place\n",
                std::chrono::duration<f64, std::milli>(finished - began).count());

    // M10 task 7.2, before the take: a crater on ground the camera passes, saved and restored
    // through the world's own persistence overlay.
    World::PersistenceReport persistence;
    const WorldVec3d crater{world.centre().x + 180.0, 0.0, world.centre().z + 140.0};
    if (Status deformed = world.deform_and_round_trip(crater, 40.0F, 9.0F, persistence);
        !deformed) {
        std::fprintf(stderr, "the persistence round trip failed: %s\n", deformed.error().message);
        return 1;
    }
    print_persistence(persistence);

    // THE PROBE COUNT IS A CHECK AND NOT A CAPTION. Printing "0 of 289 probes disagree" and
    // carrying on regardless is the false green this project has shipped before: a restore that
    // came back lossy would print "289 of 289" in the middle of a page of output nobody reads
    // line by line, and `just capture-world` would still write a video of a world whose
    // persistence does not round trip. `samples_compared` is checked too, because "0 of 0 disagree"
    // is what a crater stamped outside every resident tile would print, and it reads like a pass.
    if (!persistence.restored || persistence.samples_compared == 0 ||
        persistence.samples_disagreeing != 0) {
        std::fprintf(stderr,
                     "m10 task 7.2 failed: the crater did not survive the overlay round trip "
                     "(%u of %u probes disagree, restored=%s)\n",
                     persistence.samples_disagreeing, persistence.samples_compared,
                     persistence.restored ? "yes" : "no");
        return 1;
    }

    Stage stage(allocator);
    const bool wants_pictures = !options.frames.empty() && !options.headless;
    if (wants_pictures) {
        if (Status opened = open_stage(stage, world, options); !opened) {
            std::fprintf(stderr, "the stage did not open: %s\n", opened.error().message);
            return 1;
        }
        if (!stage.available()) {
            std::fprintf(stderr,
                         "\nno graphics device answered (%s), so no frames were written.\n"
                         "The world above was still generated, cooked, claimed and placed — every\n"
                         "producer in this artefact runs on the processor and only the picture "
                         "needs a device.\n",
                         stage.absence());
            // AND THAT IS A FAILURE WHEN A BUDGET WAS TO BE JUDGED WITH A DEVICE DRAWING.
            // `m11a:world-budget-on-a-device`'s whole subject is the submit-and-wait band that
            // only a device produces; returning 0 here would report "the budget held" for a run in
            // which nothing was drawn, which is the same shape as a suite that skips and is read as
            // a pass. The headless claim is the one every machine can judge and it is a separate
            // criterion.
            if (options.budget_ms > 0.0F) {
                std::fprintf(stderr,
                             "--budget-ms was given without --headless, so this run was to be "
                             "judged WITH a device drawing, and none answered. That is not a "
                             "budget held.\n");
                return 1;
            }
            return 0;
        }
    }

    const u64 frames = static_cast<u64>(options.seconds * static_cast<f32>(options.fps));
    const u32 still_frame =
        options.still_frame != 0 ? options.still_frame : static_cast<u32>((frames * 27) / 100);

    Take take(allocator);
    std::printf("\n=== the take: %llu frames, one simulated day ===\n",
                static_cast<unsigned long long>(frames));
    if (Status ran = run_take(world, stage, options, frames, still_frame, wants_pictures, take);
        !ran) {
        std::fprintf(stderr, "the take failed: %s\n", ran.error().message);
        return 1;
    }

    print_budget(take);
    // WHAT THIS ARTEFACT STREAMS, AT THE END OF THE TAKE RATHER THAN AT THE START, because eviction
    // is something a take does and not something a build reports. `m11a:world-streams` reads these
    // two numbers; both are zero and the criterion is RED, which is the honest state of
    // `world-partition-and-streaming` in this tree.
    const World::StreamingReport streamed = world.streaming();
    std::printf("\n=== world-partition-and-streaming: what this artefact streams ===\n");
    std::printf("  tiles_cooked: %u  tiles_resident: %u  evicted: %u  stitched_vertices: %u\n",
                streamed.tiles_cooked, streamed.tiles_resident, streamed.tiles_evicted,
                streamed.stitched_vertices);
    if (!options.budget.empty() &&
        !write_budget(options.budget, take.costs, take.day, take.sun, take.rain, take.drawn)) {
        return 1;
    }
    const bool budget_held = options.budget_ms <= 0.0F || judge_budget(take, options.budget_ms);

    if (wants_pictures) {
        // WHAT THE FRAME RAN, READ OFF THE FRAME. M11.c task 3.2: the report names the post stages
        // the LAST frame actually executed, in order, out of the manifest the frame emitted — not
        // out of what this program configured. The two differ exactly when something is wrong, and
        // that is the case this line exists for.
        if (!take.drawn.empty() && take.drawn[take.drawn.size() - 1].manifest_valid) {
            const cy::rendering::assembly::CaptureManifest& manifest =
                take.drawn[take.drawn.size() - 1].manifest;
            std::printf("\n=== the frame, as the frame reported it ===\n");
            std::printf(
                "  %u pass(es) declared, %u post stage(s), exposure %.2f stops, jitter %s\n",
                take.drawn[take.drawn.size() - 1].frame_passes, manifest.stage_count,
                static_cast<double>(-manifest.ev100),
                manifest.jitter_pinned ? "pinned" : "free-running");
            std::printf("  chain:");
            for (u32 step = 0; step < manifest.stage_count; ++step) {
                std::printf(" %s", cy::rendering::post_stage_name(manifest.stages[step].stage));
            }
            std::printf(
                "\n  NO anti-aliasing stage: nothing in this tree records the frame's "
                "temporal pass.\n");
        }
        std::printf("\n  %llu frames written to %s, vulkan validation errors: %u\n",
                    static_cast<unsigned long long>(frames), options.frames.c_str(),
                    take.validation_errors);
        if (take.validation_errors != 0) {
            std::fprintf(stderr, "  THAT NUMBER SHOULD BE ZERO.\n");
            return 1;
        }
    }
    return budget_held ? 0 : 1;
}
