#pragma once
// The material model, its parameter storage, and the GPU material table. Task 4.2.4.
//
// `rendering-materials-and-shading` — "Material model": a material is "an authored definition, a
// compiled **material program** produced by the material compiler, a parameter block, and a
// resource block", parameters are **static** (part of the program's structure) or **runtime** (data
// that changes without recompilation), and instances "reference a program and override a subset of
// runtime parameters", creatable at runtime with no compilation.
//
// ================================================================================================
// WHAT M3 BUILDS AND WHAT M7 BUILDS, BECAUSE THE SPLIT IS THE INTERESTING PART
// ================================================================================================
//
// design.md §5: "M3 integrates Slang → SPIR-V and builds the caching, permutation and
// reflection-driven binding around it. It does NOT build the material compiler — that is M7's."
//
// So there is no closure graph here, no lowering, and no code generation. What is here is the shape
// a compiled program HAS — a parameter layout, a shading model, a blend mode, a permutation key —
// and the storage its parameters live in. A material authored as data at M3 fills that shape
// directly; a material compiled from a closure graph at M7 fills the same shape, and nothing
// downstream changes. The seam is that `MaterialProgram` is a description rather than a compiler
// output type.
//
// ================================================================================================
// PARAMETER STORAGE: WHY A TABLE AND NOT A DESCRIPTOR SET PER MATERIAL
// ================================================================================================
//
// "Material parameters and resource references SHALL live in the GPU material table, addressed by a
// material identifier carried in GPU scene instance data", and the scenario is "WHEN a
// GPU-generated draw shades a pixel THEN it SHALL index the material table using the instance's
// material identifier, with no per-object descriptor binding."
//
// That requirement is what makes GPU-driven rendering possible at all: a draw generated by a
// compute shader has no CPU in the loop to bind anything. So a material's parameters are BYTES AT
// AN INDEX, the index is `GpuInstance::material`, and the table is one buffer.
//
// Three consequences worth stating because each is a decision:
//
//   * Every material's parameter block is the same size (`kMaterialBlockBytes`), so the index is a
//     multiplication rather than an offset table the shader would have to read first.
//   * A parameter is addressed by a `ParameterId` — a hash of its name, computed at compile time —
//     and resolved to an offset once, when the program is described. "Parameter names SHALL resolve
//     to compile-time identifiers; per-frame string lookup SHALL NOT be required."
//   * Changing a parameter marks ONE material's range dirty, and `MaterialTable::dirty_range()`
//     merges them into one transfer. "Parameter updates SHALL be batched: changed materials SHALL
//     be collected during Prepare and uploaded in one transfer."
//
// Textures are indices into bindless descriptor arrays, stored in the block like any other
// parameter, "with per-material descriptor sets used only on the compatibility path".

#include <cy/core/base/expected.h>
#include <cy/core/base/types.h>
#include <cy/core/math/vec.h>
#include <cy/core/memory/allocator.h>
#include <cy/core/memory/array.h>
#include <cy/core/values/name.h>
#include <cy/rendering/material/brdf.h>
#include <cy/servers/render/types.h>

namespace cy::rendering {

using render::BlendMode;
using render::ShadingModel;

// --- Parameters ---------------------------------------------------------------------------------

enum class ParameterKind : u8 {
    Float = 0,
    Vec2,
    Vec3,
    Vec4,
    /// A linear colour. Distinct from `Vec4` so validation can say "this slot wants a colour and
    /// you gave it a data texture", and so an editor shows a swatch.
    Color,
    Int,
    Bool,
    /// A bindless index into the global texture array. Four bytes, like everything else — a texture
    /// parameter is a number, which is what makes a GPU-generated draw able to reach it.
    Texture,
    Count,
};

[[nodiscard]] const char* parameter_kind_name(ParameterKind kind) noexcept;
[[nodiscard]] u32 parameter_byte_size(ParameterKind kind) noexcept;

/// A parameter's compile-time identity: the FNV-1a hash of its name.
///
/// A hash rather than an index because it must survive a program being recompiled with parameters
/// added or reordered — an index would silently address a different parameter. Collisions are
/// refused at description time (`MaterialProgram::add_parameter`), which is the only moment a
/// collision is cheap.
using ParameterId = u32;

[[nodiscard]] constexpr ParameterId parameter_id(const char* name) noexcept {
    u32 hash = 2166136261U;
    for (const char* cursor = name; *cursor != '\0'; ++cursor) {
        hash ^= static_cast<u32>(static_cast<unsigned char>(*cursor));
        hash *= 16777619U;
    }
    return hash;
}

/// One parameter in a program's layout.
struct MaterialParameter {
    Name name;
    ParameterId id = 0;
    ParameterKind kind = ParameterKind::Float;
    /// Byte offset within the material's parameter block. Assigned by `add_parameter`, aligned to
    /// the parameter's own size so the block matches std430 without padding rules being restated.
    u32 offset = 0;
    /// STATIC parameters are part of the program's structure — a permutation is compiled per
    /// distinct value — and RUNTIME parameters are data. "The classification SHALL be derived by
    /// the compiler from how a parameter is used"; at M3 the author states it, and M7's compiler
    /// derives it and fills in the same field.
    bool is_static = false;
    /// Set when something actually reads the parameter. Written by validation, read by the report
    /// that names parameters "declared but unused".
    bool referenced = true;
};

// --- Programs -----------------------------------------------------------------------------------

/// How many bytes one material's parameter block occupies in the table.
///
/// Fixed, so the shader's address is `material_index * kMaterialBlockBytes` and nothing has to be
/// looked up before the parameters can be read. 256 bytes is sixty-four four-byte parameters, which
/// covers the standard material with room; a program that needs more is refused at description
/// time rather than overflowing into its neighbour.
inline constexpr u32 kMaterialBlockBytes = 256;

/// The most parameters one program declares. A bound rather than a growth policy, for the same
/// reason: the block is fixed and a program cannot outgrow it anyway.
inline constexpr u32 kMaxMaterialParameters = 64;

/// A compiled material program, as far as everything downstream is concerned.
///
/// At M3 a program is described by hand or by the standard material; at M7 the material compiler
/// produces one. Nothing that consumes a program can tell which, and that is the seam.
class MaterialProgram {
public:
    explicit MaterialProgram(Allocator& allocator) noexcept;

    MaterialProgram(const MaterialProgram&) = delete;
    MaterialProgram& operator=(const MaterialProgram&) = delete;

    [[nodiscard]] Status initialize(Name name, ShadingModel model, BlendMode blend) noexcept;

    /// Declare a parameter. Refuses a duplicate name, a hash collision with a different name, and a
    /// block that would overflow — all three at the only moment they are cheap.
    [[nodiscard]] Expected<ParameterId, Error> add_parameter(const char* name, ParameterKind kind,
                                                             bool is_static = false) noexcept;

    [[nodiscard]] const MaterialParameter* find(ParameterId id) const noexcept;
    [[nodiscard]] Span<const MaterialParameter> parameters() const noexcept {
        return parameters_.span();
    }

    [[nodiscard]] Name name() const noexcept { return name_; }
    [[nodiscard]] ShadingModel model() const noexcept { return model_; }
    [[nodiscard]] BlendMode blend() const noexcept { return blend_; }
    [[nodiscard]] u32 block_bytes() const noexcept { return used_bytes_; }

    /// The permutation count this program's static parameters imply: two per boolean, and one
    /// otherwise. What `rendering-materials-and-shading`'s "materials whose permutation count
    /// exceeds a budget" is measured against.
    [[nodiscard]] u64 permutation_count() const noexcept;

    /// The mask a pipeline is keyed by. Bit `n` is the `n`th static boolean parameter, in
    /// declaration order — which is stable because declaration order is, and is what makes two runs
    /// select the same permutation.
    [[nodiscard]] u32 static_bool_count() const noexcept;

    /// Mark a parameter as read by the program's code. The shader system calls it from reflection;
    /// validation reports the ones nobody called it for.
    void mark_referenced(ParameterId id, bool referenced) noexcept;

private:
    Name name_;
    ShadingModel model_ = ShadingModel::Lit;
    BlendMode blend_ = BlendMode::Opaque;
    Array<MaterialParameter> parameters_;
    u32 used_bytes_ = 0;
};

// --- The GPU material table -----------------------------------------------------------------

/// One material's slot in the table, and the writes that reach it.
///
/// A material INSTANCE in the specification's sense is a slot plus a program: "a material instance
/// references a program and overrides a subset of runtime parameters. Instances SHALL be creatable
/// at runtime without compilation, and any number SHALL share one program." Creating one here is
/// allocating a slot and copying the parent's block — no compilation, and nothing to invalidate.
class MaterialTable {
public:
    explicit MaterialTable(Allocator& allocator) noexcept;

    MaterialTable(const MaterialTable&) = delete;
    MaterialTable& operator=(const MaterialTable&) = delete;

    /// `capacity` materials, each `kMaterialBlockBytes`. Fixed for the same reason the GPU scene's
    /// is: the buffer's address is baked into descriptors and a device-side draw holds an index
    /// into it.
    [[nodiscard]] Status initialize(u32 capacity) noexcept;

    /// Allocate a slot. `index` is what goes into `GpuInstance::material`.
    [[nodiscard]] Expected<u32, Error> allocate() noexcept;
    /// Allocate a slot initialised as a copy of `parent`'s — the material-instance case.
    [[nodiscard]] Expected<u32, Error> instantiate(u32 parent) noexcept;
    [[nodiscard]] Status release(u32 index) noexcept;

    /// Write a parameter into a slot. The program supplies the offset and the kind; a write whose
    /// kind does not match the declaration is refused, because a `Vec3` written where a `Float` was
    /// declared silently overwrites the two parameters after it.
    [[nodiscard]] Status set_float(const MaterialProgram& program, u32 index, ParameterId id,
                                   f32 value) noexcept;
    [[nodiscard]] Status set_vec4(const MaterialProgram& program, u32 index, ParameterId id,
                                  Vec4 value) noexcept;
    [[nodiscard]] Status set_color(const MaterialProgram& program, u32 index, ParameterId id,
                                   Vec4 linear_color) noexcept;
    [[nodiscard]] Status set_texture(const MaterialProgram& program, u32 index, ParameterId id,
                                     u32 bindless_index) noexcept;
    [[nodiscard]] Status set_int(const MaterialProgram& program, u32 index, ParameterId id,
                                 i32 value) noexcept;
    [[nodiscard]] Status set_bool(const MaterialProgram& program, u32 index, ParameterId id,
                                  bool value) noexcept;

    [[nodiscard]] Expected<f32, Error> get_float(const MaterialProgram& program, u32 index,
                                                 ParameterId id) const noexcept;
    [[nodiscard]] Expected<Vec4, Error> get_vec4(const MaterialProgram& program, u32 index,
                                                 ParameterId id) const noexcept;
    [[nodiscard]] Expected<u32, Error> get_texture(const MaterialProgram& program, u32 index,
                                                   ParameterId id) const noexcept;

    /// The whole table, for the upload. Contiguous, so a transfer is one copy.
    [[nodiscard]] Span<const u8> bytes() const noexcept { return storage_.span(); }

    /// The byte range that changed since `clear_dirty()`, as one interval.
    ///
    /// ONE INTERVAL, DELIBERATELY. "Changed materials SHALL be collected during Prepare and
    /// uploaded in one transfer" — one transfer is the requirement, and a list of intervals would
    /// be several. The cost is uploading the untouched slots between two changed ones; the benefit
    /// is a single `vkCmdCopyBuffer` whatever changed, and at 256 bytes a material the interval is
    /// small unless the two changed materials are far apart, which is the case where a whole-table
    /// upload was going to be cheapest anyway.
    [[nodiscard]] bool dirty_range(u32& out_offset, u32& out_size) const noexcept;
    void clear_dirty() noexcept;

    [[nodiscard]] u32 capacity() const noexcept { return capacity_; }
    [[nodiscard]] u32 live() const noexcept { return live_; }

private:
    [[nodiscard]] Expected<u32, Error> resolve_offset(const MaterialProgram& program, u32 index,
                                                      ParameterId id,
                                                      ParameterKind expected) const noexcept;
    void mark_dirty(u32 offset, u32 size) noexcept;

    Array<u8> storage_;
    Array<u32> free_slots_;
    u32 capacity_ = 0;
    u32 next_ = 0;
    u32 live_ = 0;
    u32 dirty_begin_ = 0;
    u32 dirty_end_ = 0;
};

}  // namespace cy::rendering
