#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""The `swift-format` gate — `testing-and-quality`, "Static analysis and formatting".

    The repository SHALL enforce, via pre-commit hooks and CI: … `swift-format` for Swift

`just quality-format-check` runs clang-format over the C++ tree and reads no Swift at all, and
`just build-editor-format` runs rustfmt over the editor. The forty Swift files this project owns —
`CyberdyneKit`, `CyberdyneMacros`, the overlay's tests, and `samples/04-character/game/`, which is
the whole evidence for M4's "no C++ gameplay" claim — were formatted by nobody.

--- WHERE THE TOOL COMES FROM ------------------------------------------------------------------------

`swift format` has been a subcommand of the Swift 6 toolchain since 6.0, and this project already
requires that toolchain: `bindings/swift/Package.swift` declares `swift-tools-version: 6.0` and three
CI jobs install it. So the gate adds **no new dependency** — it uses the compiler that is already a
prerequisite of building the Swift bindings at all.

--- WHERE THE TOOLCHAIN ACTUALLY IS, WHICH IS NOT ON PATH --------------------------------------------

**This was nearly written as an unrunnable gate.** `command -v swift` finds nothing on the machine
M11.d was worked on, and the first version of this file reported "no Swift toolchain" and exited 2.
It was wrong: there is a **Swift 6.3.3** toolchain installed through `swiftly`, whose environment
line goes into `~/.profile` and therefore reaches only a LOGIN shell.
`bindings/swift/tools/cy_swift_module.py` already knew — it runs every Swift command as
`bash -lc '. ${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh; …'` and says why in its own
header — and this gate now resolves the same way, through the same environment file, so the compiler
that builds the Swift bindings and the formatter that checks them are the same installation.

The lesson is the one this project keeps paying for in the other direction: **a check that reports
"not available" is as wrong as one that reports a false pass if it looked in the wrong place.**

Resolution order, first match wins, and only the first when it is set: `CY_SWIFT_FORMAT`, a
`swift-format` binary on PATH, `swift` on PATH, then `swift` through the swiftly environment.
Naming a binary and then silently running a different one would be worse than failing, which is the
rule `just _tool-resolve` already states for clang-format and clang-tidy.

Exit 2 means the gate DID NOT RUN, which `tools/quality/selftest.py` tells apart from exit 1: "no
toolchain" is not "formatted correctly", and a gate that cannot find its tool must not look like a
gate that passed.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]

#: The Swift this project owns. `bindings/swift/.build/` holds swift-syntax, which is somebody else's.
ROOTS = (
    "bindings/swift/Sources/CyberdyneKit",
    "bindings/swift/Sources/CyberdyneMacros",
    "bindings/swift/Tests",
    "bindings/swift/fixtures",
    "samples/04-character/game",
)

#: Generated by `tools/gen/`, whose output `just generate-check` holds to its generator. A hand
#: reformat here is erased by the next run, so the generator is where its formatting is decided.
EXCLUDED = ("bindings/swift/Sources/CyberdyneCore/Generated",)

CONFIGURATION = ".swift-format"

INSTALL = {
    "linux": "https://swift.org/install/linux — or `apt install swiftlang` where it is packaged",
    "darwin": "xcode-select --install, or a toolchain from https://swift.org/install/macos",
    "windows": "winget install Swift.Toolchain",
}


#: How `bindings/swift/tools/cy_swift_module.py` reaches the toolchain, quoted from it so the two
#: cannot drift: swiftly writes its environment line to ~/.profile, which only a login shell reads.
SWIFTLY_ENV = "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"


def run(command: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    """Run a resolved command, through the swiftly environment when that is where the tool lives."""
    if command[0] == "@swiftly":
        line = ". " + SWIFTLY_ENV + " 2>/dev/null; " + " ".join(f"'{word}'" for word in command[1:])
        return subprocess.run(["bash", "-lc", line], cwd=cwd, capture_output=True, text=True)
    return subprocess.run(command, cwd=cwd, capture_output=True, text=True)


def resolve() -> list[str] | None:
    """The command that runs swift-format, or None when no Swift toolchain can be reached."""
    override = os.environ.get("CY_SWIFT_FORMAT")
    if override:
        return [override]
    binary = shutil.which("swift-format")
    if binary:
        return [binary]
    swift = shutil.which("swift")
    if swift:
        return [swift, "format"]
    # Not on PATH is not the same as not installed. See the header: swiftly's toolchain reaches only
    # a login shell, and this project's own Swift build already goes through that environment file.
    probe = run(["@swiftly", "swift", "--version"])
    if probe.returncode == 0:
        return ["@swiftly", "swift", "format"]
    return None


def swift_files(root: Path) -> list[str]:
    found = []
    for name in ROOTS:
        base = root / name
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.swift")):
            relative = str(path.relative_to(root))
            if any(relative.startswith(prefix) for prefix in EXCLUDED):
                continue
            if "/.build/" in relative:
                continue
            found.append(relative)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=REPOSITORY)
    parser.add_argument("--fix", action="store_true", help="format in place instead of checking")
    arguments = parser.parse_args()

    root = arguments.root.resolve()
    configuration = root / CONFIGURATION
    if not configuration.is_file():
        print(f"swift-format-gate: {CONFIGURATION} is missing.", file=sys.stderr)
        print("  A formatting gate with no committed configuration enforces whatever the tool's",
              file=sys.stderr)
        print("  default happens to be on the machine it ran on, which is not a gate.",
              file=sys.stderr)
        return 1

    files = swift_files(root)
    if not files:
        print("swift-format-gate: no Swift sources found under the declared roots. The gate read",
              file=sys.stderr)
        print("  nothing, so it cannot say the tree is clean.", file=sys.stderr)
        return 1

    command = resolve()
    if command is None:
        platform = "darwin" if sys.platform == "darwin" else "win32" if os.name == "nt" else "linux"
        print("swift-format-gate: no Swift toolchain, on PATH or through swiftly.", file=sys.stderr)
        print(f"  {len(files)} Swift file(s) went unchecked, which is NOT a pass.", file=sys.stderr)
        print(f"  Install Swift 6: {INSTALL.get(platform, INSTALL['linux'])}", file=sys.stderr)
        print("  Or name one: CY_SWIFT_FORMAT=/path/to/swift-format", file=sys.stderr)
        return 2  # distinct from 1, so the selftest can tell "unrun" from "failed"

    action = ["format", "--in-place"] if arguments.fix else ["lint", "--strict"]
    finished = run([*command, *action, "--configuration", str(configuration), "--parallel", *files],
                   cwd=root)

    if finished.returncode != 0:
        print(f"swift-format-gate: {CONFIGURATION} is not what these files are formatted to.",
              file=sys.stderr)
        print(finished.stdout, file=sys.stderr)
        print(finished.stderr, file=sys.stderr)
        print("  Fix it with: just quality-swift-format --fix", file=sys.stderr)
        return 1

    version = run([*command, "--version"])
    print(f"swift-format-gate: {len(files)} Swift file(s) match {CONFIGURATION} "
          f"(swift-format {version.stdout.strip() or 'version unreported'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
