#!/usr/bin/env python3
"""Build a Swift game module, one shared library per hot-reload generation. Task 3.7.

    cy_swift_module.py --probe
    cy_swift_module.py --work DIR --generation 0=<sources> --generation 1=<sources> --out DIR
    cy_swift_module.py --test            # `swift test` over bindings/swift

--- WHY THIS EXISTS RATHER THAN A `swift build` IN A RECIPE ---------------------------------------

Two things the ordinary command cannot do, and both are requirements rather than conveniences.

1. A UNIQUE SWIFT `-module-name` PER GENERATION. M4's hot-reload spike measured this: name-based
   type lookup (`Codable`, `_typeByName`, reflection) is process-global and first-registration-wins,
   so with two resident images both named `CyGame`, the NEW image asking for its OWN behaviour class
   got the OLD image's metadata — both addresses printed. Since the reload model never unloads an
   image, same-named generations accumulate. A unique FILENAME is not enough; the module name has to
   differ too, and `cy/abi/module.h` says the loader cannot enforce it, so the build must.

   SwiftPM sets `-module-name` from the TARGET name, and a target cannot be renamed per build. So
   this driver writes a small package whose target is `CyGame_g<N>` and builds that. Everything else
   — the dependency graph, the macro plugin, the module cache — is SwiftPM's, which is what
   `swift-scripting` asks for: "swift build, swift test, Xcode, and VS Code with SourceKit-LSP SHALL
   work with no custom toolchain".

2. SOURCING THE TOOLCHAIN. `swiftly` writes its environment line to `~/.profile`, which only login
   shells read; a CMake custom command's shell is not one. Every invocation here goes through
   `bash -lc '. <env.sh>; ...'`, which is exactly what `just env-doctor` tells a developer to do and
   what it cannot do on their behalf.

--- WHY ONE WORK DIRECTORY FOR EVERY GENERATION ---------------------------------------------------

The generations share `.build`, so swift-syntax and the macro plugin are compiled once and each
further generation is an incremental build of one target and a link. Building each generation in its
own directory would recompile the plugin every time, which is about twenty seconds each.
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys

PACKAGE = pathlib.Path(__file__).resolve().parents[1]
REPOSITORY = PACKAGE.parents[1]
SWIFTLY_ENV = "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"

# SwiftPM's scratch directory, moved OUT of the source tree.
#
# By default it is `bindings/swift/.build`, and leaving it there breaks a gate: `just
# quality-format-check` walks `bindings/` and prunes build trees BY NAME, and swift-syntax's C shim
# headers are not formatted to this project's .clang-format. So a machine that had ever run
# `swift test` would fail the formatting gate on a third party's headers. Under `build/` it is
# pruned, gitignored, and beside every other build tree.
SCRATCH = REPOSITORY / "build" / "swift-package"

MANIFEST = """\
// swift-tools-version: 6.0
// GENERATED by bindings/swift/tools/cy_swift_module.py. One target, named for its generation.
import PackageDescription

let package = Package(
    name: "{target}",
    products: [.library(name: "{target}", type: .dynamic, targets: ["{target}"])],
    dependencies: [.package(path: "{package}")],
    // A path dependency's package IDENTITY is its directory name, not the name in its manifest —
    // `bindings/swift` is identified as "swift". So the identity is substituted in rather than
    // written as "CyberdyneKit", which is what SwiftPM would reject.
    targets: [.target(name: "{target}", dependencies: [
        .product(name: "CyberdyneKit", package: "{identity}"),
    ])]
)
"""


def swift(arguments: list[str], cwd: pathlib.Path | None = None) -> subprocess.CompletedProcess:
    """Run a Swift command through a login-shell environment that has the toolchain on PATH."""
    command = ". " + SWIFTLY_ENV + " 2>/dev/null; " + " ".join(f"'{item}'" for item in arguments)
    return subprocess.run(["bash", "-lc", command], cwd=cwd, check=False, text=True,
                          capture_output=True)


def probe() -> int:
    result = swift(["swift", "--version"])
    if result.returncode != 0:
        sys.stderr.write("no Swift toolchain: `swift --version` failed.\n")
        sys.stderr.write(result.stderr)
        return 1
    sys.stdout.write(result.stdout.strip().splitlines()[0] + "\n")
    return 0


def build_generation(work: pathlib.Path, index: int, sources: pathlib.Path,
                     out: pathlib.Path, configuration: str) -> pathlib.Path:
    target = f"CyGame_g{index}"
    manifest = work / "Package.swift"
    manifest.write_text(MANIFEST.format(target=target, package=PACKAGE,
                                        identity=PACKAGE.name))

    # A fresh source directory per generation, rather than one directory whose contents change:
    # SwiftPM keys its incremental state on the target name, and a target that never existed before
    # is never stale.
    target_sources = work / "Sources" / target
    if target_sources.exists():
        shutil.rmtree(target_sources)
    target_sources.mkdir(parents=True)
    for item in sorted(sources.glob("*.swift")):
        shutil.copy2(item, target_sources / item.name)

    result = swift(["swift", "build", "-c", configuration, "--product", target], cwd=work)
    if result.returncode != 0:
        sys.stderr.write(f"generation {index} did not build:\n{result.stdout}{result.stderr}")
        raise SystemExit(2)

    built = work / ".build" / configuration / f"lib{target}.so"
    if not built.exists():
        raise SystemExit(f"generation {index}: {built} was not produced")
    out.mkdir(parents=True, exist_ok=True)
    # A DIFFERENT PATH PER GENERATION, which `BehaviourRuntime::reload` requires: `dlopen` of a path
    # already open returns the SAME image, so reloading over one file would silently reload nothing.
    destination = out / f"lib{target}.so"
    shutil.copy2(built, destination)
    return destination


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build a Swift game module per generation.")
    parser.add_argument("--probe", action="store_true", help="report the toolchain and exit")
    parser.add_argument("--test", action="store_true", help="run `swift test` over the package")
    parser.add_argument("--work", type=pathlib.Path)
    parser.add_argument("--out", type=pathlib.Path)
    parser.add_argument("--configuration", default="debug", choices=["debug", "release"])
    parser.add_argument("--generation", action="append", default=[], metavar="N=DIR")
    arguments = parser.parse_args(argv)

    if arguments.probe:
        return probe()
    if arguments.test:
        result = swift(["swift", "test", "--package-path", str(PACKAGE),
                        "--scratch-path", str(SCRATCH)])
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode
    if not arguments.work or not arguments.out or not arguments.generation:
        parser.error("--work, --out and at least one --generation are required")

    arguments.work.mkdir(parents=True, exist_ok=True)
    for entry in arguments.generation:
        index, _, directory = entry.partition("=")
        built = build_generation(arguments.work, int(index), pathlib.Path(directory),
                                 arguments.out, arguments.configuration)
        print(f"    generation {index}  {built}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
