#!/usr/bin/env python3
"""Build a Swift game module, one shared library per hot-reload generation. Task 3.7.

    cy_swift_module.py --probe
    cy_swift_module.py --work DIR --generation 0=<sources> --generation 1=<sources> --out DIR
    cy_swift_module.py --test            # `swift test` over bindings/swift

Set CY_SWIFT_DISABLE_SANDBOX=1 when a containing development sandbox refuses SwiftPM's nested
sandbox. Ordinary builds keep SwiftPM's default.

--- WHY THIS EXISTS RATHER THAN A `swift build` IN A RECIPE ---------------------------------------

Two things the ordinary command cannot do, and both are requirements rather than conveniences.

1. A UNIQUE SWIFT `-module-name` PER GENERATION. M4's hot-reload spike measured this: name-based
   type lookup (`Codable`, `_typeByName`, reflection) is process-global and first-registration-wins,
   so with two resident images both named `CyGame`, the NEW image asking for its OWN behaviour class
   got the OLD image's metadata — both addresses printed. Since the reload model never unloads an
   image, same-named generations accumulate. A unique FILENAME is not enough; the module name has to
   differ too, and `cy/abi/module.h` says the loader cannot enforce it, so the build must.

   SwiftPM sets `-module-name` from the TARGET name, and a target cannot be renamed per build. So
   this driver writes a small package whose target is `CyGame_g<N>` and builds that. Everything else
   — the dependency graph, the macro plugin, the module cache — is SwiftPM's, which is what
   `swift-scripting` asks for: "swift build, swift test, Xcode, and VS Code with SourceKit-LSP SHALL
   work with no custom toolchain".

2. SOURCING THE TOOLCHAIN. `swiftly` writes its environment line to `~/.profile`, which only login
   shells read; a CMake custom command's shell is not one. Every invocation here goes through
   `bash -lc '. <env.sh>; ...'`, which is exactly what `just env-doctor` tells a developer to do and
   what it cannot do on their behalf.

--- WHY ONE WORK DIRECTORY FOR EVERY GENERATION ---------------------------------------------------

The generations share `.build`, so swift-syntax and the macro plugin are compiled once and each
further generation is an incremental build of one target and a link. Building each generation in its
own directory would recompile the plugin every time, which is about twenty seconds each.
"""

from __future__ import annotations

import argparse
import contextlib
import getpass
import os
import pathlib
import shutil
import signal
import subprocess
import sys
import tempfile

PACKAGE = pathlib.Path(__file__).resolve().parents[1]
REPOSITORY = PACKAGE.parents[1]
SWIFTLY_ENV = "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh"

# SwiftPM's scratch directory, moved OUT of the source tree.
#
# By default it is `bindings/swift/.build`, and leaving it there breaks a gate: `just
# quality-format-check` walks `bindings/` and prunes build trees BY NAME, and swift-syntax's C shim
# headers are not formatted to this project's .clang-format. So a machine that had ever run
# `swift test` would fail the formatting gate on a third party's headers. Under `build/` it is
# pruned, gitignored, and beside every other build tree.
SCRATCH = REPOSITORY / "build" / "swift-package"

MANIFEST = """\
// swift-tools-version: 6.0
// GENERATED by bindings/swift/tools/cy_swift_module.py. One target, named for its generation.
import PackageDescription

let package = Package(
    name: "{target}",
    platforms: [.macOS(.v14)],
    products: [.library(name: "{target}", type: .dynamic, targets: ["{target}"])],
    dependencies: [.package(path: "{package}")],
    // A path dependency's package IDENTITY is its directory name, not the name in its manifest —
    // `bindings/swift` is identified as "swift". So the identity is substituted in rather than
    // written as "CyberdyneKit", which is what SwiftPM would reject.
    targets: [.target(name: "{target}", dependencies: [
        .product(name: "CyberdyneKit", package: "{identity}"),
    ])]
)
"""


# ONE SWIFTPM BUILD AT A TIME PER USER. Every package shares SwiftPM's per-user cache
# (`~/.cache/org.swift.swiftpm`), and two builds resolving swift-syntax at once race on its
# prebuilts manifest: the loser fails with "prebuilts/swift-syntax/... already exists in file
# system". Ninja schedules the samples' game modules concurrently, so the lock is taken here, where
# every caller passes through, rather than in each CMakeLists.
SWIFTPM_LOCK = pathlib.Path(tempfile.gettempdir()) / f"cy-swiftpm-{getpass.getuser()}.lock"


@contextlib.contextmanager
def swiftpm_lock():
    try:
        import fcntl
    except ImportError:  # No flock on Windows, where no sample builds a Swift module.
        yield
        return
    with SWIFTPM_LOCK.open("a") as handle:
        fcntl.flock(handle, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)


# THE BUILD SYSTEM IS NAMED, NOT INHERITED FROM THE TOOLCHAIN.
#
# Swift 6.4 changed SwiftPM's default from its native build system to Swift Build, and on Linux Swift
# Build's planner intermittently dies with signal 11 in libdispatch (`_dispatch_event_loop_drain`,
# null dereference, right after swift-syntax resolves; swiftlang/swift-build#1786). Every crash CI
# recorded was a job on the image's own Swift 6.4; no job on a pinned 6.0.3 ever crashed, and
# `--build-system native` is accepted by every toolchain this package supports. Naming it also keeps
# `--show-bin-path` agreeing with the build, since the two systems place products differently.
BUILD_SYSTEM = ["--build-system", "native"]

# A SWIFT COMMAND THAT THE TOOLCHAIN ITSELF CRASHED IS RUN AGAIN, A BOUNDED NUMBER OF TIMES. A crash
# signal says nothing about the sources, so a second run is a fair question; a compile error is an
# ordinary non-zero exit and is never retried. SIGINT, SIGTERM and SIGKILL are a person or a
# scheduler stopping the build, which a retry would defy.
CRASH_SIGNALS = frozenset({"SIGSEGV", "SIGBUS", "SIGILL", "SIGABRT", "SIGFPE", "SIGTRAP"})
CRASH_RETRIES = 2


def crash_signal(returncode: int) -> str | None:
    """The crash signal that ended a Swift command, or None when it exited on its own.

    The command runs under `bash -lc`, so a child killed by signal N is reported as 128 + N, and a
    process that `bash` replaced with `exec` is reported by Python as -N.
    """
    if returncode < 0:
        number = -returncode
    elif 128 < returncode < 128 + 65:
        number = returncode - 128
    else:
        return None
    try:
        name = signal.Signals(number).name
    except ValueError:
        return None
    return name if name in CRASH_SIGNALS else None


def run_swift(command: str, cwd: pathlib.Path | None) -> subprocess.CompletedProcess:
    """Run one shell command, again when a crash signal ended it, up to CRASH_RETRIES times."""
    def once() -> subprocess.CompletedProcess:
        return subprocess.run(["bash", "-lc", command], cwd=cwd, check=False, text=True,
                              capture_output=True)

    result = once()
    attempt, attempts = 1, CRASH_RETRIES + 1
    while (crashed := crash_signal(result.returncode)) and attempt < attempts:
        attempt += 1
        sys.stderr.write(f"cy_swift_module: the Swift toolchain died on {crashed} (exit "
                         f"{result.returncode}), a crash rather than a compile error; running it "
                         f"again, attempt {attempt} of {attempts}\n")
        result = once()
    return result


def swift(arguments: list[str], cwd: pathlib.Path | None = None) -> subprocess.CompletedProcess:
    """Run a Swift command through a login-shell environment that has the toolchain on PATH."""
    if arguments[:2] in (["swift", "build"], ["swift", "test"]):
        arguments = [*arguments[:2], *BUILD_SYSTEM, *arguments[2:]]
    if os.environ.get("CY_SWIFT_DISABLE_SANDBOX") == "1" and arguments[:2] == ["swift", "build"]:
        arguments = [*arguments[:2], "--disable-sandbox", *arguments[2:]]
    command = ". " + SWIFTLY_ENV + " 2>/dev/null; " + " ".join(f"'{item}'" for item in arguments)
    with swiftpm_lock():
        return run_swift(command, cwd)


# SWIFTPM'S STATE BELONGS TO THE TOOLCHAIN THAT WROTE IT. A scratch directory written by one Swift
# and read by an older one is refused outright: Swift 6.4 writes `workspace-state.json` version 7 and
# 6.0.3 throws "unknown 'WorkspaceStateStorage' version '7'". CI restores build trees from caches,
# and the jobs that built with the runner image's 6.4 now build with the pinned 6.0.3, so a restored
# tree would fail every game module; a developer who changes toolchains meets the same thing. The
# scratch directory is stamped with the `swift --version` line that wrote it, and discarded when the
# toolchain differs. Only SwiftPM's own state goes: the sources and the copied libraries stay.
TOOLCHAIN_STAMP = ".cy-swift-toolchain"


def toolchain_identity() -> str | None:
    """The first line `swift --version` prints, or None when no toolchain answers."""
    result = swift(["swift", "--version"])
    if result.returncode != 0 or not result.stdout.strip():
        return None
    return result.stdout.strip().splitlines()[0]


def forget_state_of_other_toolchains(scratch: pathlib.Path, stamp: pathlib.Path,
                                     identity: str | None) -> None:
    """Remove `scratch` when `stamp` names a toolchain other than `identity`, then stamp it."""
    if identity is None:
        return
    previous = stamp.read_text(encoding="utf-8").strip() if stamp.exists() else None
    if previous != identity and scratch.exists():
        sys.stderr.write(f"cy_swift_module: {scratch} was built by "
                         f"{previous or 'an unrecorded toolchain'}, not {identity}; removing it\n")
        shutil.rmtree(scratch)
    stamp.parent.mkdir(parents=True, exist_ok=True)
    stamp.write_text(identity + "\n", encoding="utf-8")


def probe() -> int:
    result = swift(["swift", "--version"])
    if result.returncode != 0:
        sys.stderr.write("no Swift toolchain: `swift --version` failed.\n")
        sys.stderr.write(result.stderr)
        return 1
    sys.stdout.write(result.stdout.strip().splitlines()[0] + "\n")
    return 0


def build_generation(work: pathlib.Path, index: int, sources: pathlib.Path,
                     out: pathlib.Path, configuration: str) -> pathlib.Path:
    target = f"CyGame_g{index}"
    manifest = work / "Package.swift"
    manifest.write_text(MANIFEST.format(target=target, package=PACKAGE,
                                        identity=PACKAGE.name))

    # A fresh source directory per generation, rather than one directory whose contents change:
    # SwiftPM keys its incremental state on the target name, and a target that never existed before
    # is never stale.
    target_sources = work / "Sources" / target
    if target_sources.exists():
        shutil.rmtree(target_sources)
    target_sources.mkdir(parents=True)
    for item in sorted(sources.glob("*.swift")):
        shutil.copy2(item, target_sources / item.name)

    result = swift(["swift", "build", "-c", configuration, "--product", target], cwd=work)
    if result.returncode != 0:
        sys.stderr.write(f"generation {index} did not build:\n{result.stdout}{result.stderr}")
        raise SystemExit(2)

    suffix = ".dylib" if sys.platform == "darwin" else ".so"
    bin_path = swift(["swift", "build", "-c", configuration, "--show-bin-path"], cwd=work)
    if bin_path.returncode != 0:
        sys.stderr.write(f"generation {index} did not report its binary path:\n"
                         f"{bin_path.stdout}{bin_path.stderr}")
        raise SystemExit(2)
    built = pathlib.Path(bin_path.stdout.strip().splitlines()[-1]) / f"lib{target}{suffix}"
    if not built.exists():
        raise SystemExit(f"generation {index}: {built} was not produced")
    out.mkdir(parents=True, exist_ok=True)
    # A DIFFERENT PATH PER GENERATION, which `BehaviourRuntime::reload` requires: `dlopen` of a path
    # already open returns the SAME image, so reloading over one file would silently reload nothing.
    destination = out / f"lib{target}.so"
    shutil.copy2(built, destination)
    return destination


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build a Swift game module per generation.")
    parser.add_argument("--probe", action="store_true", help="report the toolchain and exit")
    parser.add_argument("--test", action="store_true", help="run `swift test` over the package")
    parser.add_argument("--work", type=pathlib.Path)
    parser.add_argument("--out", type=pathlib.Path)
    parser.add_argument("--configuration", default="debug", choices=["debug", "release"])
    parser.add_argument("--generation", action="append", default=[], metavar="N=DIR")
    arguments = parser.parse_args(argv)

    if arguments.probe:
        return probe()
    if arguments.test:
        forget_state_of_other_toolchains(SCRATCH, SCRATCH.parent / f"swift-package{TOOLCHAIN_STAMP}",
                                         toolchain_identity())
        result = swift(["swift", "test", "--package-path", str(PACKAGE),
                        "--scratch-path", str(SCRATCH)])
        sys.stdout.write(result.stdout)
        sys.stderr.write(result.stderr)
        return result.returncode
    if not arguments.work or not arguments.out or not arguments.generation:
        parser.error("--work, --out and at least one --generation are required")

    arguments.work.mkdir(parents=True, exist_ok=True)
    forget_state_of_other_toolchains(arguments.work / ".build", arguments.work / TOOLCHAIN_STAMP,
                                     toolchain_identity())
    for entry in arguments.generation:
        index, _, directory = entry.partition("=")
        built = build_generation(arguments.work, int(index), pathlib.Path(directory),
                                 arguments.out, arguments.configuration)
        print(f"    generation {index}  {built}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
