# cmake/embed.cmake — compile a file's bytes into a target as a constant array.
#
# M11.e (issue #86). CyberUI's interface font is data the engine carries, as the built-in bitmap font
# before it was, but unlike that 6x13 grid it is an 86 KB OpenType file, and a committed C array of
# it would be a second copy of deps/fonts/NotoSans-Latin-VF.ttf for a reviewer to keep in step. This
# writes the array at configure time from the one file, and re-runs the configure when it changes.
#
#   cy_embed_file(<target> INPUT <file> SYMBOL <c identifier> NAMESPACE <c++ namespace>)
#
# adds a generated `<symbol>.cpp` to <target> defining
#
#   namespace <namespace> { extern const unsigned char <symbol>[]; extern const unsigned long long <symbol>_size; }
#
# which the target's own sources declare and read. No header is generated: the declaration belongs
# beside the code that gives the bytes a meaning.

include_guard(GLOBAL)

function(cy_embed_file target)
    cmake_parse_arguments(PARSE_ARGV 1 arg "" "INPUT;SYMBOL;NAMESPACE" "")
    if(NOT arg_INPUT OR NOT arg_SYMBOL OR NOT arg_NAMESPACE)
        message(FATAL_ERROR "cy_embed_file(${target}): INPUT, SYMBOL and NAMESPACE are required")
    endif()
    if(NOT EXISTS "${arg_INPUT}")
        message(FATAL_ERROR "cy_embed_file(${target}): ${arg_INPUT} does not exist")
    endif()
    file(READ "${arg_INPUT}" hex HEX)
    string(LENGTH "${hex}" digits)
    math(EXPR size "${digits} / 2")
    # Sixteen bytes a line, so the generated file is diffable and no line is a megabyte long. CMake's
    # regular expressions have no `{n}`, so the sixteen pairs are spelled out by string(REPEAT).
    string(REPEAT "[0-9a-f][0-9a-f]" 16 sixteen)
    string(REGEX REPLACE "(${sixteen})" "\\1\n    " hex "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    set(output "${CMAKE_CURRENT_BINARY_DIR}/embedded/${arg_SYMBOL}.cpp")
    file(RELATIVE_PATH relative "${CMAKE_SOURCE_DIR}" "${arg_INPUT}")
    # Appended piece by piece rather than set() as a list: a list joins on the semicolons C++ needs.
    set(content "// Generated by cmake/embed.cmake from ${relative}. Do not edit.\n")
    string(APPEND content "namespace ${arg_NAMESPACE} {\n")
    string(APPEND content "extern const unsigned char ${arg_SYMBOL}[];\n")
    string(APPEND content "extern const unsigned long long ${arg_SYMBOL}_size;\n")
    string(APPEND content "alignas(16) const unsigned char ${arg_SYMBOL}[] = {\n    ${bytes}\n};\n")
    string(APPEND content "const unsigned long long ${arg_SYMBOL}_size = ${size}ULL;\n")
    string(APPEND content "}  // namespace ${arg_NAMESPACE}\n")
    # Written only when it changes, so a configure that reads the same font rebuilds nothing.
    file(CONFIGURE OUTPUT "${output}" CONTENT "${content}" @ONLY)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${arg_INPUT}")
    target_sources(${target} PRIVATE "${output}")
endfunction()
