#include <cy/import/pipeline.h>

#include <cy/core/assets/cooked.h>
#include <cy/core/assets/file.h>
#include <cy/core/jobs/job_system.h>
#include <cy/core/jobs/parallel.h>
#include <cy/import/fbx.h>
#include <cy/import/gltf.h>
#include <cy/import/obj.h>
#include <cy/import/primitive.h>
#include <cy/import/texture.h>

#include <chrono>
#include <cstring>

#include <vector>

namespace cy::import {
namespace {

/// The bundle's own format version. A cache entry written by another version is a miss, which the
/// derivation key already guarantees — the pipeline's version is part of it — so this is a
/// belt-and-braces check that costs four bytes.
constexpr u32 kBundleVersion = 1;

/// The version of the PIPELINE, distinct from any importer's.
///
/// It is a contribution to every derivation key this pipeline produces, so that a change to how a
/// result is bundled, published or named re-cooks the project rather than serving entries laid out
/// the old way. An importer's own version covers its own output; this covers everything around it.
constexpr u32 kPipelineVersion = 1;

void put_u32(Array<u8>& out, u32 value) noexcept {
    for (u32 index = 0; index < 4; ++index) {
        (void)out.push_back(static_cast<u8>((value >> (index * 8U)) & 0xFFU));
    }
}

[[nodiscard]] u32 get_u32(const u8* data) noexcept {
    u32 value = 0;
    for (u32 index = 0; index < 4; ++index) {
        value |= static_cast<u32>(data[index]) << (index * 8U);
    }
    return value;
}

/// `<root>/<relative>` in a fixed buffer, refusing anything that does not fit.
[[nodiscard]] Status join_native(std::string_view root, std::string_view relative, char* out,
                                 usize capacity) noexcept {
    const usize needed = root.size() + 1 + relative.size();
    if (needed + 1 > capacity) {
        return fail(ErrorCode::OutOfRange, "a native path longer than this build's buffer");
    }
    usize written = 0;
    if (!root.empty()) {
        std::memcpy(out, root.data(), root.size());
        written = root.size();
        if (out[written - 1] != '/') {
            out[written++] = '/';
        }
    }
    std::memcpy(out + written, relative.data(), relative.size());
    written += relative.size();
    out[written] = '\0';
    return ok();
}

/// One sub-asset in a cached bundle. The public spellings are `encode_import_bundle` and
/// `decode_import_bundle`, at the bottom of this file; these are what they call.
[[nodiscard]] Status encode_bundle(const ImportResult& result, Array<u8>& out) noexcept {
    put_u32(out, kBundleVersion);
    put_u32(out, static_cast<u32>(result.assets().size()));
    for (const SubAsset& produced : result.assets()) {
        const std::string_view name = produced.view();
        put_u32(out, static_cast<u32>(name.size()));
        if (Status appended =
                out.append(Span<const u8>(reinterpret_cast<const u8*>(name.data()), name.size()));
            !appended) {
            return appended;
        }
        put_u32(out, static_cast<u32>(produced.kind));
        put_u32(out, produced.primary ? 1U : 0U);
        put_u32(out, static_cast<u32>(produced.payload.size()));
        if (Status appended =
                out.append(Span<const u8>(produced.payload.data(), produced.payload.size()));
            !appended) {
            return appended;
        }
    }
    // Diagnostics are NOT bundled, and that is deliberate. A warning is about the source and is
    // regenerated by re-running the importer; storing it would mean a cache hit reported warnings
    // for a state of the file that may no longer exist, which is worse than reporting none.
    return ok();
}

[[nodiscard]] Status decode_bundle(Span<const u8> payload, ImportResult& out) noexcept {
    if (payload.size() < 8 || get_u32(payload.data()) != kBundleVersion) {
        return fail(ErrorCode::InvalidArgument, "a cached import bundle this build does not read");
    }
    const usize count = get_u32(payload.data() + 4);
    usize cursor = 8;
    for (usize index = 0; index < count; ++index) {
        if (cursor + 4 > payload.size()) {
            return fail(ErrorCode::InvalidArgument, "a bundle that ends inside a sub-asset");
        }
        const usize name_length = get_u32(payload.data() + cursor);
        cursor += 4;
        if (cursor + name_length + 12 > payload.size()) {
            return fail(ErrorCode::InvalidArgument, "a bundle that ends inside a sub-asset");
        }
        const std::string_view name(reinterpret_cast<const char*>(payload.data() + cursor),
                                    name_length);
        cursor += name_length;
        const auto kind = static_cast<assets::AssetKind>(get_u32(payload.data() + cursor));
        const bool primary = get_u32(payload.data() + cursor + 4) != 0;
        const usize payload_length = get_u32(payload.data() + cursor + 8);
        cursor += 12;
        if (cursor + payload_length > payload.size()) {
            return fail(ErrorCode::InvalidArgument, "a bundle that ends inside a payload");
        }
        Array<u8> bytes;
        if (Status appended = bytes.append(Span<const u8>(payload.data() + cursor, payload_length));
            !appended) {
            return appended;
        }
        cursor += payload_length;
        if (Status added = out.add(kind, name, std::move(bytes), primary); !added) {
            return added;
        }
    }
    if (cursor != payload.size()) {
        return fail(ErrorCode::InvalidArgument, "a bundle with trailing bytes");
    }
    return ok();
}

[[nodiscard]] u64 now_micros() noexcept {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return static_cast<u64>(std::chrono::duration_cast<std::chrono::microseconds>(now).count());
}

void copy_into(char* out, usize capacity, std::string_view text) noexcept {
    const usize length = text.size() < capacity - 1 ? text.size() : capacity - 1;
    if (length != 0) {
        std::memcpy(out, text.data(), length);
    }
    out[length] = '\0';
}

}  // namespace

// --- The resolver --------------------------------------------------------------------------------

FileImportResolver::FileImportResolver(std::string_view project_root,
                                       const assets::VirtualPath& source,
                                       ImportResult& result) noexcept
    : project_root_(project_root), result_(&result) {
    const std::string_view parent = source.parent();
    // A source at the project root has no parent, and normalising an empty string is an error, so
    // the empty path is left as it is — which is exactly "the root".
    if (!parent.empty()) {
        Expected<assets::VirtualPath, Error> directory = assets::VirtualPath::normalise(parent);
        if (directory) {
            directory_ = directory.value();
        }
    }
}

Expected<Span<const u8>, Error> FileImportResolver::read(std::string_view path) noexcept {
    // Relative to the source's own directory first, then the project root. That is the order every
    // content pipeline uses and the order an artist expects: a `.bin` beside a `.gltf` wins over a
    // file of the same name at the top of the project.
    assets::VirtualPath resolved;
    if (!directory_.empty()) {
        Expected<assets::VirtualPath, Error> beside = directory_.join(path);
        if (beside) {
            resolved = beside.value();
        }
    }
    if (resolved.empty()) {
        Expected<assets::VirtualPath, Error> absolute = assets::VirtualPath::normalise(path);
        if (!absolute) {
            return make_unexpected(absolute.error());
        }
        resolved = absolute.value();
    }

    for (const Buffer& buffer : buffers_) {
        if (buffer.path == resolved) {
            return Span<const u8>(buffer.bytes.data(), buffer.bytes.size());
        }
    }

    char native[assets::kMaxPathLength * 2] = {};
    if (Status joined = join_native(project_root_, resolved.view(), native, sizeof(native));
        !joined) {
        return make_unexpected(joined.error());
    }

    Buffer buffer;
    buffer.path = resolved;
    if (Status read = assets::fs::read_whole(native, buffer.bytes); !read) {
        // Fall back to the project root when the file was not beside the source. Two lookups rather
        // than one guess, because a missing file and a file in the other place are different
        // answers and only one of them is a diagnostic.
        Expected<assets::VirtualPath, Error> absolute = assets::VirtualPath::normalise(path);
        if (!absolute) {
            return make_unexpected(read.error());
        }
        char fallback[assets::kMaxPathLength * 2] = {};
        if (Status joined =
                join_native(project_root_, absolute.value().view(), fallback, sizeof(fallback));
            !joined) {
            return make_unexpected(joined.error());
        }
        if (Status second = assets::fs::read_whole(fallback, buffer.bytes); !second) {
            return make_unexpected(second.error());
        }
        buffer.path = absolute.value();
    }

    const assets::ContentHash digest =
        assets::content_hash(buffer.bytes.data(), buffer.bytes.size());
    if (Status recorded = result_->add_dependency(buffer.path.view(), digest); !recorded) {
        return make_unexpected(recorded.error());
    }
    if (Status pushed = buffers_.push_back(std::move(buffer)); !pushed) {
        return make_unexpected(pushed.error());
    }
    const Buffer& stored = buffers_[buffers_.size() - 1];
    return Span<const u8>(stored.bytes.data(), stored.bytes.size());
}

Status FileImportResolver::observe(std::string_view name,
                                   const assets::ContentHash& digest) noexcept {
    return result_->add_dependency(name, digest);
}

// --- The pipeline --------------------------------------------------------------------------------

/// Everything one asset's import carries between its phases.
struct ImportPipeline::Prepared {
    assets::VirtualPath source;
    ImportSettings settings;
    Importer* importer = nullptr;
    ImportRecord record;
    ImportOptions options;
    assets::DerivationKey key;
    assets::ContentHash source_hash;
    Array<u8> bytes;
    AssetImportOutcome outcome;
    /// Set when `prepare` answered the whole question from the cache.
    bool from_cache = false;
    Array<u8> cached_payload;
};

ImportPipeline::ImportPipeline(ImporterRegistry& registry, assets::DerivedCache& cache) noexcept
    : registry_(&registry), cache_(&cache) {}

Status ImportPipeline::set_project_root(std::string_view path) noexcept {
    if (path.size() >= sizeof(project_root_)) {
        return fail(ErrorCode::OutOfRange, "a project root longer than this build's buffer");
    }
    copy_into(project_root_, sizeof(project_root_), path);
    return ok();
}

Status ImportPipeline::set_output_directory(std::string_view path) noexcept {
    if (path.size() >= sizeof(output_directory_)) {
        return fail(ErrorCode::OutOfRange, "an output directory longer than this build's buffer");
    }
    copy_into(output_directory_, sizeof(output_directory_), path);
    return output_directory_[0] == '\0' ? ok() : assets::fs::create_directories(output_directory_);
}

Status ImportPipeline::prepare(const assets::VirtualPath& source, const ImportSettings& settings,
                               Prepared& out) noexcept {
    out.source = source;
    out.settings = settings;
    copy_into(out.outcome.source, AssetImportOutcome::kNameCapacity, source.view());

    out.importer = registry_->find_for_source(source);
    if (out.importer == nullptr) {
        copy_into(out.outcome.cache_reason, AssetImportOutcome::kNameCapacity,
                  "no importer claims this extension");
        out.outcome.errors = 1;
        return ok();
    }
    const ImporterInfo info = out.importer->info();
    copy_into(out.outcome.importer, sizeof(out.outcome.importer), info.name);
    // A property of the FORMAT, copied onto every row so that a cache HIT reports the same absent
    // steps a miss does — diagnostics are not bundled, so a per-import diagnostic would say nothing
    // on the second run of an unchanged project. M8.a task 3.3.
    out.outcome.steps = info.steps;

    char native[assets::kMaxPathLength * 2] = {};
    if (Status joined = join_native(project_root_, source.view(), native, sizeof(native));
        !joined) {
        return joined;
    }
    if (Status read = assets::fs::read_whole(native, out.bytes); !read) {
        copy_into(out.outcome.cache_reason, AssetImportOutcome::kNameCapacity,
                  "the source could not be read");
        out.outcome.errors = 1;
        return ok();
    }
    out.source_hash = assets::content_hash(out.bytes.data(), out.bytes.size());

    // The record, if there is one. Its options are the ones a re-import uses unless the caller
    // supplied a set, which is what makes "open the dialog, change nothing, re-import" a no-op.
    Expected<assets::VirtualPath, Error> record_path = import_record_path_for(source);
    if (!record_path) {
        return make_unexpected(record_path.error());
    }
    char record_native[assets::kMaxPathLength * 2] = {};
    if (Status joined = join_native(project_root_, record_path.value().view(), record_native,
                                    sizeof(record_native));
        !joined) {
        return joined;
    }
    Array<u8> record_bytes;
    const OptionsSchema schema = out.importer->schema();
    if (assets::fs::exists(record_native) && assets::fs::read_whole(record_native, record_bytes)) {
        Expected<ImportRecord, Error> parsed =
            ImportRecord::parse(std::string_view(reinterpret_cast<const char*>(record_bytes.data()),
                                                 record_bytes.size()),
                                &schema);
        if (parsed) {
            out.record = std::move(parsed.value());
        }
    }
    if (out.record.importer().empty()) {
        Expected<ImportRecord, Error> created = ImportRecord::create(info.name, info.version);
        if (!created) {
            return make_unexpected(created.error());
        }
        out.record = std::move(created.value());
    }
    out.record.set_importer_version(info.version);
    out.record.set_source_hash(out.source_hash);

    // The options in force: the caller's when supplied, the record's otherwise. Copied into
    // `Prepared` so the request can point at something that outlives the record's own mutation.
    const ImportOptions& in_force =
        settings.options != nullptr ? *settings.options : out.record.options();
    for (usize index = 0; index < in_force.size(); ++index) {
        if (Status set = out.options.set(schema, in_force.name_at(index), in_force.value_at(index));
            !set) {
            return set;
        }
    }

    ImportRequest request;
    request.source = source;
    request.bytes = Span<const u8>(out.bytes.data(), out.bytes.size());
    request.options = &out.options;
    request.variant = settings.variant;
    request.profile = settings.profile;
    Expected<assets::DerivationKey, Error> key =
        import_derivation_key(info, schema, request, out.source_hash);
    if (!key) {
        return make_unexpected(key.error());
    }
    // The pipeline's own version joins the importer's, so that a change to how results are bundled
    // or published re-cooks rather than serving entries laid out the old way.
    assets::DerivationKeyBuilder combined;
    combined.producer(assets::DerivedKind::Import, "pipeline", kPipelineVersion)
        .source("import", key.value().digest);
    Expected<assets::DerivationKey, Error> final_key = combined.finish();
    if (!final_key) {
        return make_unexpected(final_key.error());
    }
    out.key = final_key.value();
    return ok();
}

Status ImportPipeline::publish(Prepared& prepared, const ImportResult& result) noexcept {
    const Span<const SubAsset> produced = result.assets();
    std::vector<cy::AssetId> ids(produced.size());
    usize minted = 0;
    if (Status bound =
            bind_sub_assets(prepared.record, result, Span<cy::AssetId>(ids.data(), ids.size()),
                            minted, prepared.settings.minting);
        !bound) {
        return bound;
    }
    prepared.outcome.minted_ids = minted;
    prepared.outcome.sub_assets = produced.size();
    prepared.outcome.profile = prepared.settings.profile;

    // THE COOK PROFILE DECIDES WHAT IS WRITTEN, NOT WHAT IS IMPORTED. M6 task 8.3.
    //
    // Every sub-asset is still produced, still bound to its id and still registered in the
    // database, because an id must not move when a project cooks for two profiles: a reference from
    // a prefab to a mesh has to resolve to the same id in a client package and in the server's copy
    // of the same prefab. What the profile changes is which cooked files reach the output — which
    // is the "content selection is a declared policy" the requirement asks for, and the level at
    // which it can be reported as bytes saved.

    // Write every cooked sub-asset. The envelope is `cy::assets::write_cooked_asset`, which is what
    // the loader checks before it hands bytes to a parser — see cooked.h for why that is separate
    // from the payload's own format.
    assets::ContentHash primary_cooked_hash;
    for (usize index = 0; index < produced.size(); ++index) {
        Array<u8> cooked;
        if (Status written = assets::write_cooked_asset(
                produced[index].kind, prepared.settings.variant,
                Span<const u8>(produced[index].payload.data(), produced[index].payload.size()),
                cooked);
            !written) {
            return written;
        }
        if (produced[index].primary) {
            // `AssetMeta::cooked_hash` is the digest of what the cook produced, and it has been
            // zero in every sidecar this project has written because nothing cooked before M5. This
            // is the first thing that does, so this is where it stops being zero.
            //
            // Computed BEFORE the profile's exclusion, and from the payload rather than from the
            // file: the sidecar is per SOURCE and not per profile, so a server cook that excluded
            // the primary must not write a zero hash into the sidecar the client cook filled in.
            primary_cooked_hash = assets::content_hash(produced[index].payload.data(),
                                                       produced[index].payload.size());
        }
        if (!profile_retains(prepared.settings.profile, produced[index].kind,
                             produced[index].view())) {
            ++prepared.outcome.excluded_sub_assets;
            prepared.outcome.excluded_bytes += cooked.size();
            continue;
        }
        prepared.outcome.cooked_bytes += cooked.size();

        if (output_directory_[0] == '\0') {
            continue;
        }
        char id_text[cy::AssetId::kTextLength + 1] = {};
        (void)ids[index].format(id_text);
        char name[cy::AssetId::kTextLength + 16] = {};
        (void)std::snprintf(name, sizeof(name), "%s.cyasset", id_text);
        char native[assets::kMaxPathLength * 2] = {};
        if (Status joined = join_native(output_directory_, name, native, sizeof(native)); !joined) {
            return joined;
        }
        if (Status written = assets::fs::write_atomic(native, cooked.data(), cooked.size());
            !written) {
            return written;
        }
    }

    // The identity record. The primary sub-asset's id is the SOURCE's id — a `.gltf` is one asset
    // that contains several, and the thing a reference to the file resolves to is its prefab.
    const SubAsset* primary = result.primary();
    cy::AssetId primary_id;
    for (usize index = 0; index < produced.size(); ++index) {
        if (&produced[index] == primary) {
            primary_id = ids[index];
        }
    }
    if (primary_id.is_nil() && !ids.empty()) {
        primary_id = ids[0];
    }
    prepared.outcome.id = primary_id;

    // EVERY sub-asset is registered, not only the primary. The database is the id-to-source index a
    // serialized reference resolves through — "WHEN a texture referenced by an imported material
    // moves THEN the reference SHALL resolve by AssetId and no re-import SHALL be needed" — and an
    // index that held only the primary could not answer a reference to a mesh inside a glTF, which
    // is most of the references a scene holds. Several ids mapping to one source is exactly right:
    // that IS what a source containing several assets means.
    for (usize index = 0; index < produced.size(); ++index) {
        if (ids[index].is_nil()) {
            continue;
        }
        assets::AssetMeta meta;
        meta.id = ids[index];
        meta.kind = produced[index].kind;
        meta.source = prepared.source;
        meta.source_hash = prepared.source_hash;
        if (Status registered = database_.register_asset(meta); !registered) {
            // A collision names both sources and is worth reporting rather than aborting the run:
            // the second asset does not import, the first is untouched, and the report says which
            // two files are involved.
            copy_into(prepared.outcome.cache_reason, AssetImportOutcome::kNameCapacity,
                      "two sources claim one asset id; see the sidecars");
            ++prepared.outcome.errors;
            break;
        }
    }

    if (project_root_[0] == '\0') {
        return ok();
    }

    // Both sidecars. See the note at the head of sidecar.h for why there are two.
    char meta_native[assets::kMaxPathLength * 2] = {};
    Expected<assets::VirtualPath, Error> meta_path = assets::meta_path_for(prepared.source);
    if (!meta_path) {
        return make_unexpected(meta_path.error());
    }
    if (Status joined =
            join_native(project_root_, meta_path.value().view(), meta_native, sizeof(meta_native));
        !joined) {
        return joined;
    }
    // The `.meta` sidecar names the SOURCE's own identity, which is its primary sub-asset's id: a
    // `.gltf` is one asset containing several, and a reference to the file resolves to its prefab.
    // The rest of the sub-assets are in the database and in the `.import` record beside it.
    assets::AssetMeta primary_meta;
    primary_meta.id = primary_id;
    primary_meta.kind = primary != nullptr ? primary->kind : assets::AssetKind::Unknown;
    primary_meta.source = prepared.source;
    primary_meta.source_hash = prepared.source_hash;
    primary_meta.cooked_hash = primary_cooked_hash;

    char meta_text[1024] = {};
    Expected<usize, Error> meta_written =
        assets::write_meta(primary_meta, meta_text, sizeof(meta_text));
    if (!meta_written) {
        return make_unexpected(meta_written.error());
    }
    if (Status written = assets::fs::write_atomic(meta_native, meta_text, meta_written.value());
        !written) {
        return written;
    }

    Expected<assets::VirtualPath, Error> record_path = import_record_path_for(prepared.source);
    if (!record_path) {
        return make_unexpected(record_path.error());
    }
    char record_native[assets::kMaxPathLength * 2] = {};
    if (Status joined = join_native(project_root_, record_path.value().view(), record_native,
                                    sizeof(record_native));
        !joined) {
        return joined;
    }
    const OptionsSchema schema = prepared.importer->schema();
    std::vector<char> record_text(prepared.record.written_size(schema) + 1, '\0');
    Expected<usize, Error> record_written =
        prepared.record.write(schema, record_text.data(), record_text.size());
    if (!record_written) {
        return make_unexpected(record_written.error());
    }
    return assets::fs::write_atomic(record_native, record_text.data(), record_written.value());
}

Expected<AssetImportOutcome, Error> ImportPipeline::import_file(
    const assets::VirtualPath& source, const ImportSettings& settings) noexcept {
    const u64 started = now_micros();
    Prepared prepared;
    if (Status prepared_status = prepare(source, settings, prepared); !prepared_status) {
        return make_unexpected(prepared_status.error());
    }
    if (prepared.importer == nullptr || prepared.outcome.errors != 0) {
        prepared.outcome.duration_micros = now_micros() - started;
        if (Status added = report_.add(prepared.outcome); !added) {
            return make_unexpected(added.error());
        }
        return prepared.outcome;
    }

    ImportResult result;
    bool have_result = false;

    if (!settings.ignore_cache) {
        // The invalidation check re-digests every dependency the entry recorded, through the same
        // resolution the resolver uses. The context travels as a void* because the cache is at
        // layer 0 and knows nothing about paths or projects — which is what lets one cache serve
        // producers whose inputs are files, assets and settings alike.
        struct Context {
            const char* root;
        };
        Context context{project_root_};
        const auto digest = [](void* user, std::string_view name, bool* found) noexcept {
            auto* self = static_cast<Context*>(user);
            char native[assets::kMaxPathLength * 2] = {};
            if (Status joined = join_native(self->root, name, native, sizeof(native)); !joined) {
                *found = false;
                return assets::ContentHash{};
            }
            Array<u8> bytes;
            if (Status read = assets::fs::read_whole(native, bytes); !read) {
                *found = false;
                return assets::ContentHash{};
            }
            *found = true;
            return assets::content_hash(bytes.data(), bytes.size());
        };

        assets::CacheResult lookup = cache_->lookup(prepared.key, digest, &context);
        prepared.outcome.cache = lookup.outcome;
        prepared.outcome.tier = lookup.tier;
        copy_into(prepared.outcome.cache_reason, AssetImportOutcome::kNameCapacity,
                  lookup.stale.empty() ? std::string_view(lookup.reason) : lookup.stale);
        if (lookup.is_hit()) {
            if (Status decoded = decode_bundle(lookup.entry.payload(), result); decoded) {
                have_result = true;
            } else {
                // A bundle this build cannot read is a miss rather than a failure. The entry stays
                // where it is; the next store overwrites it with one this build wrote.
                prepared.outcome.cache = assets::CacheOutcome::Corrupt;
            }
        }
    }

    if (!have_result) {
        FileImportResolver resolver(project_root_, source, result);
        ImportRequest request;
        request.source = source;
        request.bytes = Span<const u8>(prepared.bytes.data(), prepared.bytes.size());
        request.options = &prepared.options;
        request.variant = settings.variant;
        request.profile = settings.profile;
        request.resolver = &resolver;
        if (Status imported = prepared.importer->import(request, result); !imported) {
            return make_unexpected(imported.error());
        }
        prepared.outcome.warnings = result.warning_count();
        prepared.outcome.errors += result.has_errors() ? 1U : 0U;

        // A failed import is NOT cached. A cached failure is a failure a developer cannot clear by
        // fixing the source, which is the worst property a build cache can have.
        if (!result.has_errors()) {
            Array<u8> bundle;
            if (Status encoded = encode_bundle(result, bundle); !encoded) {
                return make_unexpected(encoded.error());
            }
            std::vector<assets::DerivedDependency> dependencies;
            dependencies.reserve(result.dependency_count());
            for (usize index = 0; index < result.dependency_count(); ++index) {
                dependencies.push_back(result.dependency(index));
            }
            assets::DerivedArtefact artefact;
            artefact.kind = assets::DerivedKind::Import;
            artefact.producer = prepared.importer->info().name;
            artefact.payload = Span<const u8>(bundle.data(), bundle.size());
            artefact.dependencies =
                Span<const assets::DerivedDependency>(dependencies.data(), dependencies.size());
            if (Status stored = cache_->store(prepared.key, artefact); !stored) {
                return make_unexpected(stored.error());
            }
        }
    }

    if (prepared.outcome.errors == 0) {
        if (Status published = publish(prepared, result); !published) {
            return make_unexpected(published.error());
        }
    }

    prepared.outcome.duration_micros = now_micros() - started;
    if (Status added = report_.add(prepared.outcome); !added) {
        return make_unexpected(added.error());
    }
    return prepared.outcome;
}

Expected<usize, Error> ImportPipeline::import_all(Span<const assets::VirtualPath> sources,
                                                  const ImportSettings& settings,
                                                  jobs::JobSystem* job_system) noexcept {
    total_.store(sources.size(), std::memory_order_relaxed);
    completed_.store(0, std::memory_order_relaxed);

    // Serial when there is no job system, and serial for one asset — dispatching a single import
    // onto a worker costs a scheduling round trip and buys nothing.
    if (job_system == nullptr || sources.size() < 2) {
        usize imported = 0;
        for (const assets::VirtualPath& source : sources) {
            if (is_cancelled()) {
                break;
            }
            if (Expected<AssetImportOutcome, Error> outcome = import_file(source, settings);
                !outcome) {
                return make_unexpected(outcome.error());
            }
            ++imported;
            completed_.store(imported, std::memory_order_relaxed);
        }
        return imported;
    }

    // Phase 1: prepare every asset serially — digesting sources and asking the cache are file
    // opens, and `DerivedCache` is documented as reachable from one thread.
    std::vector<Prepared> prepared(sources.size());
    std::vector<bool> needs_import(sources.size(), false);
    std::vector<ImportResult> results(sources.size());
    struct Context {
        const char* root;
    };
    Context context{project_root_};
    const auto digest = [](void* user, std::string_view name, bool* found) noexcept {
        auto* self = static_cast<Context*>(user);
        char native[assets::kMaxPathLength * 2] = {};
        if (Status joined = join_native(self->root, name, native, sizeof(native)); !joined) {
            *found = false;
            return assets::ContentHash{};
        }
        Array<u8> bytes;
        if (Status read = assets::fs::read_whole(native, bytes); !read) {
            *found = false;
            return assets::ContentHash{};
        }
        *found = true;
        return assets::content_hash(bytes.data(), bytes.size());
    };

    for (usize index = 0; index < sources.size(); ++index) {
        if (is_cancelled()) {
            return usize{0};
        }
        if (Status ready = prepare(sources[index], settings, prepared[index]); !ready) {
            return make_unexpected(ready.error());
        }
        if (prepared[index].importer == nullptr || prepared[index].outcome.errors != 0) {
            continue;
        }
        if (!settings.ignore_cache) {
            assets::CacheResult lookup = cache_->lookup(prepared[index].key, digest, &context);
            prepared[index].outcome.cache = lookup.outcome;
            prepared[index].outcome.tier = lookup.tier;
            copy_into(prepared[index].outcome.cache_reason, AssetImportOutcome::kNameCapacity,
                      lookup.stale.empty() ? std::string_view(lookup.reason) : lookup.stale);
            if (lookup.is_hit() && decode_bundle(lookup.entry.payload(), results[index])) {
                continue;
            }
        }
        needs_import[index] = true;
    }

    // Phase 2: the importers, in parallel. This is where the time is — a mesh import is seconds of
    // welding, tangent generation and simplification — and it is the only phase that touches
    // nothing shared but the filesystem it reads.
    std::vector<u8> failed(sources.size(), 0);
    auto body = [&](const jobs::TaskContext&, u64 begin, u64 end) noexcept {
        for (u64 index = begin; index < end; ++index) {
            const auto slot = static_cast<usize>(index);
            if (!needs_import[slot] || is_cancelled()) {
                continue;
            }
            FileImportResolver resolver(project_root_, prepared[slot].source, results[slot]);
            ImportRequest request;
            request.source = prepared[slot].source;
            request.bytes =
                Span<const u8>(prepared[slot].bytes.data(), prepared[slot].bytes.size());
            request.options = &prepared[slot].options;
            request.variant = settings.variant;
            request.profile = settings.profile;
            request.resolver = &resolver;
            if (Status imported = prepared[slot].importer->import(request, results[slot]);
                !imported) {
                failed[slot] = 1;
            }
        }
    };
    // A grain of one: an import is far too coarse to batch, and a partition of several would make
    // one slow asset hold up the workers that could have taken the others.
    if (Status ran = jobs::parallel_for(*job_system, sources.size(), 1, body, "import"); !ran) {
        return make_unexpected(ran.error());
    }

    // Phase 3: store, publish and report, serially and in source order — so a run's report is the
    // same whatever order the workers happened to finish in.
    usize imported = 0;
    for (usize index = 0; index < sources.size(); ++index) {
        if (prepared[index].importer == nullptr || prepared[index].outcome.errors != 0) {
            if (Status added = report_.add(prepared[index].outcome); !added) {
                return make_unexpected(added.error());
            }
            continue;
        }
        if (failed[index] != 0) {
            ++prepared[index].outcome.errors;
            if (Status added = report_.add(prepared[index].outcome); !added) {
                return make_unexpected(added.error());
            }
            continue;
        }
        prepared[index].outcome.warnings = results[index].warning_count();
        prepared[index].outcome.errors += results[index].has_errors() ? 1U : 0U;

        if (needs_import[index] && !results[index].has_errors()) {
            Array<u8> bundle;
            if (Status encoded = encode_bundle(results[index], bundle); !encoded) {
                return make_unexpected(encoded.error());
            }
            std::vector<assets::DerivedDependency> dependencies;
            dependencies.reserve(results[index].dependency_count());
            for (usize slot = 0; slot < results[index].dependency_count(); ++slot) {
                dependencies.push_back(results[index].dependency(slot));
            }
            assets::DerivedArtefact artefact;
            artefact.kind = assets::DerivedKind::Import;
            artefact.producer = prepared[index].importer->info().name;
            artefact.payload = Span<const u8>(bundle.data(), bundle.size());
            artefact.dependencies =
                Span<const assets::DerivedDependency>(dependencies.data(), dependencies.size());
            if (Status stored = cache_->store(prepared[index].key, artefact); !stored) {
                return make_unexpected(stored.error());
            }
        }
        if (prepared[index].outcome.errors == 0) {
            if (Status published = publish(prepared[index], results[index]); !published) {
                return make_unexpected(published.error());
            }
        }
        if (Status added = report_.add(prepared[index].outcome); !added) {
            return make_unexpected(added.error());
        }
        ++imported;
        completed_.store(imported, std::memory_order_relaxed);
    }
    return imported;
}

// --- The built-ins -------------------------------------------------------------------------------

namespace {
GltfImporter g_gltf;
FbxImporter g_fbx;
ObjImporter g_obj;
TextureImporter g_texture;
PrimitiveImporter g_primitive;
}  // namespace

Status register_builtin_importers(ImporterRegistry& registry) noexcept {
    // Static instances because an importer holds no state — `Importer::import` is a pure function
    // of its request — so one serves every worker and every pipeline. An importer that DID hold
    // state would have to be constructed per pipeline, and its registration would say so.
    if (Status registered = registry.register_importer(&g_gltf); !registered) {
        return registered;
    }
    if (Status registered = registry.register_importer(&g_fbx); !registered) {
        return registered;
    }
    // M8.a task 3.2. OBJ joins the other two model importers in the SAME registry, so it reaches
    // the same pipeline, the same `import_derivation_key` and the same `DerivedCache` — which is
    // task 3.4, and is the property M6's gate measured going wrong when two importer binaries with
    // two keys shared one cache. There is nowhere here to put a second key.
    if (Status registered = registry.register_importer(&g_obj); !registered) {
        return registered;
    }
    // M8.a task 2.1. A generated primitive is registered here, beside the three that parse a file,
    // because that is what makes it indistinguishable from them: one registry, one lookup by
    // extension, one derivation key. A caller that builds a registry gets `.cyprim` without asking
    // for it, which is what "a delivered feature is on by default" means for this one.
    if (Status registered = registry.register_importer(&g_primitive); !registered) {
        return registered;
    }
    return registry.register_importer(&g_texture);
}

Status encode_import_bundle(const ImportResult& result, Array<u8>& out) noexcept {
    return encode_bundle(result, out);
}

Status decode_import_bundle(Span<const u8> payload, ImportResult& out) noexcept {
    return decode_bundle(payload, out);
}

}  // namespace cy::import
